the input device is not a TTY
the input device is not a TTY
the input device is not a TTY
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
[2025-06-20 14:04:01] Start cron job
本次資料成功處理完畢
[2025-06-20 14:05:01] Start cron job
本次資料成功處理完畢
[2025-06-20 14:06:01] Start cron job
本次資料成功處理完畢
[2025-06-20 14:07:01] 本次資料成功處理完畢
[2025-06-20 14:08:01] 本次資料成功處理完畢
[2025-06-20 14:09:01] 本次資料成功處理完畢
[2025-06-20 14:10:01] 本次資料成功處理完畢
[2025-06-20 14:11:01] 本次資料成功處理完畢
[2025-06-20 14:12:02] 本次資料成功處理完畢
[2025-06-20 14:13:01] 本次資料成功處理完畢
[2025-06-20 14:14:01] 本次資料成功處理完畢
[2025-06-20 14:15:01] 本次資料成功處理完畢
[2025-06-20 14:16:01] 本次資料成功處理完畢
[2025-06-20 14:17:01] 本次資料成功處理完畢
[2025-06-20 14:18:01] 本次資料成功處理完畢
[2025-06-20 14:19:02] 本次資料成功處理完畢
[2025-06-20 14:20:01] 本次資料成功處理完畢
[2025-06-20 14:21:01] 本次資料成功處理完畢
[2025-06-20 14:22:01] 本次資料成功處理完畢
[2025-06-20 14:23:01] 本次資料成功處理完畢
[2025-06-20 14:24:01] 本次資料成功處理完畢
[2025-06-20 14:25:01] 本次資料成功處理完畢
[2025-06-20 14:26:01] 本次資料成功處理完畢
[2025-06-20 14:27:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 118B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 2.3s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 6.63kB done
#6 DONE 0.1s

#7 [3/4] RUN pip install requests psycopg2 pandas
#7 7.197 Collecting requests
#7 8.245   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#7 8.580      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 168.8 kB/s eta 0:00:00
#7 9.167 Collecting psycopg2
#7 9.329   Downloading psycopg2-2.9.10.tar.gz (385 kB)
#7 9.752      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 956.4 kB/s eta 0:00:00
#7 9.933   Preparing metadata (setup.py): started
#7 11.71   Preparing metadata (setup.py): finished with status 'done'
#7 12.96 Collecting pandas
#7 13.07   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
#7 15.51      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 5.1 MB/s eta 0:00:00
#7 15.91 Collecting urllib3<3,>=1.21.1
#7 16.02   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#7 16.04      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 10.8 MB/s eta 0:00:00
#7 16.86 Collecting charset_normalizer<4,>=2
#7 16.96   Downloading charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
#7 17.00      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 4.8 MB/s eta 0:00:00
#7 17.15 Collecting idna<4,>=2.5
#7 17.25   Downloading idna-3.10-py3-none-any.whl (70 kB)
#7 17.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 6.8 MB/s eta 0:00:00
#7 17.46 Collecting certifi>=2017.4.17
#7 17.57   Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
#7 17.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 10.0 MB/s eta 0:00:00
#7 19.81 Collecting numpy>=1.20.3
#7 19.91   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#7 21.59      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 9.2 MB/s eta 0:00:00
#7 21.87 Collecting tzdata>=2022.1
#7 21.98   Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
#7 22.03      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 7.4 MB/s eta 0:00:00
#7 22.53 Collecting pytz>=2020.1
#7 22.78   Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
#7 22.84      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 9.3 MB/s eta 0:00:00
#7 23.05 Collecting python-dateutil>=2.8.2
#7 23.16   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#7 23.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 4.4 MB/s eta 0:00:00
#7 23.66 Collecting six>=1.5
#7 23.97   Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
#7 24.04 Building wheels for collected packages: psycopg2
#7 24.04   Building wheel for psycopg2 (setup.py): started
#7 48.15   Building wheel for psycopg2 (setup.py): finished with status 'done'
#7 48.15   Created wheel for psycopg2: filename=psycopg2-2.9.10-cp38-cp38-linux_x86_64.whl size=485114 sha256=88ce33c66e51ab7b2f227a2e6b55dc5d9599aa8a4013a609f646908f3ca9e738
#7 48.15   Stored in directory: /root/.cache/pip/wheels/85/b7/48/d6ffc48322fa70ef973e9ca95a5e012f2d71efadd88d847865
#7 48.16 Successfully built psycopg2
#7 48.69 Installing collected packages: pytz, urllib3, tzdata, six, psycopg2, numpy, idna, charset_normalizer, certifi, requests, python-dateutil, pandas
[2025-06-20 14:28:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 118B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.4s

#3 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/4] WORKDIR /app
#4 CACHED

#5 [internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.1s

#6 [3/4] RUN pip install requests psycopg2 pandas
#6 7.197 Collecting requests
#6 8.245   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#6 8.580      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 168.8 kB/s eta 0:00:00
#6 9.167 Collecting psycopg2
#6 9.329   Downloading psycopg2-2.9.10.tar.gz (385 kB)
#6 9.752      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 956.4 kB/s eta 0:00:00
#6 9.933   Preparing metadata (setup.py): started
#6 11.71   Preparing metadata (setup.py): finished with status 'done'
#6 12.96 Collecting pandas
#6 13.07   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
#6 15.51      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 5.1 MB/s eta 0:00:00
#6 15.91 Collecting urllib3<3,>=1.21.1
#6 16.02   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#6 16.04      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 10.8 MB/s eta 0:00:00
#6 16.86 Collecting charset_normalizer<4,>=2
#6 16.96   Downloading charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
#6 17.00      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 4.8 MB/s eta 0:00:00
#6 17.15 Collecting idna<4,>=2.5
#6 17.25   Downloading idna-3.10-py3-none-any.whl (70 kB)
#6 17.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 6.8 MB/s eta 0:00:00
#6 17.46 Collecting certifi>=2017.4.17
#6 17.57   Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
#6 17.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 10.0 MB/s eta 0:00:00
#6 19.81 Collecting numpy>=1.20.3
#6 19.91   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#6 21.59      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 9.2 MB/s eta 0:00:00
#6 21.87 Collecting tzdata>=2022.1
#6 21.98   Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
#6 22.03      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 7.4 MB/s eta 0:00:00
#6 22.53 Collecting pytz>=2020.1
#6 22.78   Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
#6 22.84      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 9.3 MB/s eta 0:00:00
#6 23.05 Collecting python-dateutil>=2.8.2
#6 23.16   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#6 23.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 4.4 MB/s eta 0:00:00
#6 23.66 Collecting six>=1.5
#6 23.97   Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
#6 24.04 Building wheels for collected packages: psycopg2
#6 24.04   Building wheel for psycopg2 (setup.py): started
#6 48.15   Building wheel for psycopg2 (setup.py): finished with status 'done'
#6 48.15   Created wheel for psycopg2: filename=psycopg2-2.9.10-cp38-cp38-linux_x86_64.whl size=485114 sha256=88ce33c66e51ab7b2f227a2e6b55dc5d9599aa8a4013a609f646908f3ca9e738
#6 48.15   Stored in directory: /root/.cache/pip/wheels/85/b7/48/d6ffc48322fa70ef973e9ca95a5e012f2d71efadd88d847865
#6 48.16 Successfully built psycopg2
#6 48.69 Installing collected packages: pytz, urllib3, tzdata, six, psycopg2, numpy, idna, charset_normalizer, certifi, requests, python-dateutil, pandas
#6 ...

#7 [internal] load build context
#7 transferring context: 15.25kB done
#7 DONE 0.1s

#6 [3/4] RUN pip install requests psycopg2 pandas
#6 69.83 Successfully installed certifi-2025.6.15 charset_normalizer-3.4.2 idna-3.10 numpy-1.24.4 pandas-2.0.3 psycopg2-2.9.10 python-dateutil-2.9.0.post0 pytz-2025.2 requests-2.32.4 six-1.17.0 tzdata-2025.2 urllib3-2.2.3
#7 69.83 Successfully installed certifi-2025.6.15 charset_normalizer-3.4.2 idna-3.10 numpy-1.24.4 pandas-2.0.3 psycopg2-2.9.10 python-dateutil-2.9.0.post0 pytz-2025.2 requests-2.32.4 six-1.17.0 tzdata-2025.2 urllib3-2.2.3
#6 69.83 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#7 69.83 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 70.69 
#6 70.69 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#6 70.69 [notice] To update, run: pip install --upgrade pip
#7 70.69 
#7 70.69 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#7 70.69 [notice] To update, run: pip install --upgrade pip
#6 DONE 71.7s
#7 DONE 71.7s

#8 [4/4] COPY . .
#8 DONE 0.1s

#8 [4/4] COPY . .
#8 DONE 0.1s

#9 exporting to image
#9 exporting layers

#9 exporting to image
#9 exporting layers
#9 exporting layers 2.8s done
#9 exporting layers 2.8s done
#9 writing image sha256:bf19a1b7b6ae285341a86ce08e6c7af32cce3fd7cc1639a85e24f9b7dd2104b0 0.0s done
#9 naming to docker.io/library/nutn-my-python 0.0s done
#9 DONE 2.9s
#9 writing image sha256:e63031ac4e4dc020bb83308106eb04e1f6a55694f361765ea91618579313c88d done
#9 naming to docker.io/library/nutn-my-python 0.0s done
#9 DONE 2.9s
本次資料成功處理完畢
本次資料成功處理完畢
[2025-06-20 14:29:01] 本次資料成功處理完畢
[2025-06-20 14:30:01] 本次資料成功處理完畢
[2025-06-20 14:31:01] 本次資料成功處理完畢
[2025-06-20 14:32:01] 本次資料成功處理完畢
[2025-06-20 14:33:01] 本次資料成功處理完畢
[2025-06-20 14:34:02] 本次資料成功處理完畢
[2025-06-20 14:35:01] 本次資料成功處理完畢
[2025-06-20 14:36:01] 本次資料成功處理完畢
[2025-06-20 14:37:01] 本次資料成功處理完畢
[2025-06-20 14:38:01] 本次資料成功處理完畢
[2025-06-20 14:39:01] 本次資料成功處理完畢
[2025-06-20 14:40:01] 本次資料成功處理完畢
[2025-06-20 14:41:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 123B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/4] WORKDIR /app
#4 CACHED

#5 [internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 15.36kB done
#6 DONE 0.0s

#7 [3/4] RUN pip install requests psycopg2 SQLAlchemy
#7 6.139 Collecting requests
#7 6.615   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#7 6.728      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 581.8 kB/s eta 0:00:00
#7 7.210 Collecting psycopg2
#7 7.306   Downloading psycopg2-2.9.10.tar.gz (385 kB)
#7 7.521      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 1.9 MB/s eta 0:00:00
#7 7.701   Preparing metadata (setup.py): started
#7 9.029   Preparing metadata (setup.py): finished with status 'done'
#7 12.40 Collecting SQLAlchemy
#7 12.50   Downloading sqlalchemy-2.0.41-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
#7 13.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 4.3 MB/s eta 0:00:00
#7 14.09 Collecting charset_normalizer<4,>=2
#7 14.19   Downloading charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
#7 14.23      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 5.9 MB/s eta 0:00:00
#7 14.44 Collecting certifi>=2017.4.17
#7 14.54   Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
#7 14.57      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 5.9 MB/s eta 0:00:00
#7 14.71 Collecting idna<4,>=2.5
#7 14.81   Downloading idna-3.10-py3-none-any.whl (70 kB)
#7 14.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 4.0 MB/s eta 0:00:00
#7 15.21 Collecting urllib3<3,>=1.21.1
#7 15.29   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#7 15.33      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 7.1 MB/s eta 0:00:00
#7 15.80 Collecting typing-extensions>=4.6.0
#7 15.90   Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
#7 15.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 1.4 MB/s eta 0:00:00
#7 17.40 Collecting greenlet>=1
#7 17.49   Downloading greenlet-3.1.1-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (605 kB)
#7 17.56      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 606.0/606.0 kB 8.5 MB/s eta 0:00:00
#7 17.66 Building wheels for collected packages: psycopg2
#7 17.67   Building wheel for psycopg2 (setup.py): started
#7 42.58   Building wheel for psycopg2 (setup.py): finished with status 'done'
#7 42.58   Created wheel for psycopg2: filename=psycopg2-2.9.10-cp38-cp38-linux_x86_64.whl size=485108 sha256=6399b8612a07343ef9a53edc975a93a2237b7843dd1b659a4c9dda606429c28d
#7 42.59   Stored in directory: /root/.cache/pip/wheels/85/b7/48/d6ffc48322fa70ef973e9ca95a5e012f2d71efadd88d847865
#7 42.60 Successfully built psycopg2
#7 43.03 Installing collected packages: urllib3, typing-extensions, psycopg2, idna, greenlet, charset_normalizer, certifi, SQLAlchemy, requests
#7 47.12 Successfully installed SQLAlchemy-2.0.41 certifi-2025.6.15 charset_normalizer-3.4.2 greenlet-3.1.1 idna-3.10 psycopg2-2.9.10 requests-2.32.4 typing-extensions-4.13.2 urllib3-2.2.3
#7 47.13 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#7 47.92 
#7 47.92 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#7 47.92 [notice] To update, run: pip install --upgrade pip
#7 DONE 48.5s

#8 [4/4] COPY . .
#8 DONE 0.2s

#9 exporting to image
#9 exporting layers
#9 exporting layers 0.8s done
#9 writing image sha256:ee97d8816f5ca9f175cce634b55365db039be89c5873ba65e9b6505e6751f83d done
#9 naming to docker.io/library/nutn-my-python 0.0s done
#9 DONE 0.9s
本次資料成功處理完畢
[2025-06-20 14:42:01] 本次資料成功處理完畢
[2025-06-20 14:43:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 129B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.0s

#3 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/4] WORKDIR /app
#4 CACHED

#5 [internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 19.17kB done
#6 DONE 0.0s

#7 [3/4] RUN pip install requests psycopg2 SQLAlchemy pandas
#7 6.052 Collecting requests
#7 6.896   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#7 7.007      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 573.0 kB/s eta 0:00:00
#7 7.477 Collecting psycopg2
#7 7.579   Downloading psycopg2-2.9.10.tar.gz (385 kB)
#7 7.774      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 2.0 MB/s eta 0:00:00
#7 7.951   Preparing metadata (setup.py): started
#7 9.257   Preparing metadata (setup.py): finished with status 'done'
#7 12.14 Collecting SQLAlchemy
#7 12.25   Downloading sqlalchemy-2.0.41-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
#7 12.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 8.3 MB/s eta 0:00:00
#7 14.03 Collecting pandas
#7 14.26   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
#7 16.61      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 4.8 MB/s eta 0:00:00
#7 17.14 Collecting urllib3<3,>=1.21.1
#7 17.24   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#7 17.29      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 5.9 MB/s eta 0:00:00
#7 17.52 Collecting idna<4,>=2.5
#7 17.63   Downloading idna-3.10-py3-none-any.whl (70 kB)
#7 17.66      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 6.2 MB/s eta 0:00:00
#7 17.88 Collecting certifi>=2017.4.17
#7 18.02   Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
#7 18.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 3.0 MB/s eta 0:00:00
#7 18.84 Collecting charset_normalizer<4,>=2
#7 18.96   Downloading charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
#7 18.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 10.4 MB/s eta 0:00:00
#7 19.36 Collecting typing-extensions>=4.6.0
#7 19.46   Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
#7 19.48      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 3.7 MB/s eta 0:00:00
#7 20.97 Collecting greenlet>=1
#7 21.09   Downloading greenlet-3.1.1-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (605 kB)
#7 21.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 606.0/606.0 kB 6.9 MB/s eta 0:00:00
#7 21.65 Collecting tzdata>=2022.1
#7 21.85   Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
#7 22.05      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 1.9 MB/s eta 0:00:00
#7 22.60 Collecting pytz>=2020.1
#7 22.82   Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
#7 22.96      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 3.6 MB/s eta 0:00:00
#7 25.17 Collecting numpy>=1.20.3
#7 25.27   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#7 28.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 4.8 MB/s eta 0:00:00
#7 28.59 Collecting python-dateutil>=2.8.2
#7 28.70   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#7 28.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 5.4 MB/s eta 0:00:00
#7 29.03 Collecting six>=1.5
#7 29.13   Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
#7 29.24 Building wheels for collected packages: psycopg2
#7 29.24   Building wheel for psycopg2 (setup.py): started
#7 54.65   Building wheel for psycopg2 (setup.py): finished with status 'done'
#7 54.65   Created wheel for psycopg2: filename=psycopg2-2.9.10-cp38-cp38-linux_x86_64.whl size=485107 sha256=e9cba4535b7a357eb718367c632997670f370cc588fdb3d69540e11ffaad32b5
#7 54.65   Stored in directory: /root/.cache/pip/wheels/85/b7/48/d6ffc48322fa70ef973e9ca95a5e012f2d71efadd88d847865
#7 54.65 Successfully built psycopg2
#7 55.45 Installing collected packages: pytz, urllib3, tzdata, typing-extensions, six, psycopg2, numpy, idna, greenlet, charset_normalizer, certifi, SQLAlchemy, requests, python-dateutil, pandas
#7 79.84 Successfully installed SQLAlchemy-2.0.41 certifi-2025.6.15 charset_normalizer-3.4.2 greenlet-3.1.1 idna-3.10 numpy-1.24.4 pandas-2.0.3 psycopg2-2.9.10 python-dateutil-2.9.0.post0 pytz-2025.2 requests-2.32.4 six-1.17.0 typing-extensions-4.13.2 tzdata-2025.2 urllib3-2.2.3
#7 79.85 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#7 80.50 
#7 80.50 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#7 80.50 [notice] To update, run: pip install --upgrade pip
#7 DONE 81.6s

#8 [4/4] COPY . .
#8 DONE 0.1s

#9 exporting to image
#9 exporting layers
#9 exporting layers 3.2s done
#9 writing image sha256:3be39177b014076bf8652c447524fdeaa7e4b037a2e0faf50afca564db301858 0.0s done
#9 naming to docker.io/library/nutn-my-python 0.0s done
#9 DONE 3.3s
本次資料成功處理完畢
[2025-06-20 14:44:01] 本次資料成功處理完畢
[2025-06-20 14:45:01] 本次資料成功處理完畢
[2025-06-20 14:46:01] 本次資料成功處理完畢
[2025-06-20 14:47:01] 本次資料成功處理完畢
[2025-06-20 14:48:01] 本次資料成功處理完畢
[2025-06-20 14:49:01] 本次資料成功處理完畢
[2025-06-20 14:50:01] 本次資料成功處理完畢
[2025-06-20 14:51:01] 本次資料成功處理完畢
[2025-06-20 14:52:01] 本次資料成功處理完畢
[2025-06-20 14:53:01] 本次資料成功處理完畢
[2025-06-20 14:54:01] 本次資料成功處理完畢
[2025-06-20 14:55:01] 本次資料成功處理完畢
[2025-06-20 14:56:01] 本次資料成功處理完畢
[2025-06-20 14:57:01] 本次資料成功處理完畢
[2025-06-20 14:58:01] 本次資料成功處理完畢
[2025-06-20 14:59:01] 本次資料成功處理完畢
[2025-06-20 15:00:01] 本次資料成功處理完畢
[2025-06-20 15:01:01] 本次資料成功處理完畢
[2025-06-20 15:02:14] 本次資料成功處理完畢
[2025-06-20 15:03:02] 本次資料成功處理完畢
[2025-06-20 15:04:01] 本次資料成功處理完畢
[2025-06-20 15:05:01] 本次資料成功處理完畢
[2025-06-20 15:06:01] 本次資料成功處理完畢
[2025-06-20 15:07:01] 本次資料成功處理完畢
[2025-06-20 15:08:01] 本次資料成功處理完畢
[2025-06-20 15:09:01] 本次資料成功處理完畢
[2025-06-20 15:10:02] 本次資料成功處理完畢
[2025-06-20 15:11:01] 本次資料成功處理完畢
[2025-06-20 15:12:01] 本次資料成功處理完畢
[2025-06-20 15:13:01] 本次資料成功處理完畢
[2025-06-20 15:14:01] 本次資料成功處理完畢
[2025-06-20 15:15:01] 本次資料成功處理完畢
[2025-06-20 15:16:01] 本次資料成功處理完畢
[2025-06-20 15:17:01] 本次資料成功處理完畢
[2025-06-20 15:18:01] 本次資料成功處理完畢
[2025-06-20 15:19:01] 本次資料成功處理完畢
[2025-06-20 15:20:02] 本次資料成功處理完畢
[2025-06-20 15:21:05] 本次資料成功處理完畢
[2025-06-20 15:22:01] 本次資料成功處理完畢
[2025-06-20 15:23:01] 本次資料成功處理完畢
[2025-06-20 15:24:01] 本次資料成功處理完畢
[2025-06-20 15:25:01] 本次資料成功處理完畢
[2025-06-20 15:26:01] 本次資料成功處理完畢
[2025-06-20 15:27:01] 本次資料成功處理完畢
[2025-06-20 15:28:01] 本次資料成功處理完畢
[2025-06-20 15:29:01] 本次資料成功處理完畢
[2025-06-20 15:30:01] 本次資料成功處理完畢
[2025-06-20 15:31:01] 本次資料成功處理完畢
[2025-06-20 15:32:01] 本次資料成功處理完畢
[2025-06-20 15:33:01] 本次資料成功處理完畢
[2025-06-20 15:36:53] 本次資料成功處理完畢
[2025-06-20 15:37:00] [2025-06-20 15:37:00] [2025-06-20 15:37:01] 本次資料成功處理完畢
本次資料成功處理完畢
本次資料成功處理完畢
[2025-06-20 15:38:01] 本次資料成功處理完畢
[2025-06-20 15:39:01] 本次資料成功處理完畢
[2025-06-20 15:40:01] 本次資料成功處理完畢
[2025-06-20 15:41:01] 本次資料成功處理完畢
[2025-06-20 15:42:01] 本次資料成功處理完畢
[2025-06-20 15:43:01] 本次資料成功處理完畢
[2025-06-20 15:44:01] 本次資料成功處理完畢
[2025-06-20 15:45:01] 本次資料成功處理完畢
[2025-06-20 15:46:01] 本次資料成功處理完畢
[2025-06-20 15:47:01] 本次資料成功處理完畢
[2025-06-20 15:48:01] 本次資料成功處理完畢
[2025-06-20 15:49:01] 本次資料成功處理完畢
[2025-06-20 15:50:01] 本次資料成功處理完畢
[2025-06-20 15:51:01] 本次資料成功處理完畢
[2025-06-20 15:52:01] 本次資料成功處理完畢
[2025-06-20 15:59:17] 本次資料成功處理完畢
[2025-06-20 16:00:02] 本次資料成功處理完畢
[2025-06-20 16:01:02] 本次資料成功處理完畢
[2025-06-20 16:02:01] 本次資料成功處理完畢
[2025-06-20 16:03:02] 本次資料成功處理完畢
[2025-06-20 16:04:01] 本次資料成功處理完畢
[2025-06-20 16:05:01] 本次資料成功處理完畢
[2025-06-20 16:06:01] 本次資料成功處理完畢
[2025-06-20 16:07:05] 本次資料成功處理完畢
[2025-06-20 16:08:02] 本次資料成功處理完畢
[2025-06-20 16:09:01] 本次資料成功處理完畢
[2025-06-20 16:10:01] 本次資料成功處理完畢
[2025-06-20 16:11:02] 本次資料成功處理完畢
[2025-06-20 16:12:02] 本次資料成功處理完畢
[2025-06-20 16:13:01] 本次資料成功處理完畢
[2025-06-20 16:14:05] 本次資料成功處理完畢
[2025-06-20 16:15:01] 本次資料成功處理完畢
[2025-06-20 16:16:02] 本次資料成功處理完畢
[2025-06-20 16:17:01] 本次資料成功處理完畢
[2025-06-20 16:18:04] 本次資料成功處理完畢
[2025-06-20 16:19:02] 本次資料成功處理完畢
[2025-06-20 16:20:01] 本次資料成功處理完畢
[2025-06-20 16:21:01] 本次資料成功處理完畢
[2025-06-20 16:22:01] 本次資料成功處理完畢
[2025-06-20 16:23:02] 本次資料成功處理完畢
[2025-06-20 16:24:02] 本次資料成功處理完畢
[2025-06-20 16:25:01] 本次資料成功處理完畢
[2025-06-20 16:26:01] 本次資料成功處理完畢
[2025-06-20 16:27:01] 本次資料成功處理完畢
[2025-06-20 16:28:01] 本次資料成功處理完畢
[2025-06-20 16:29:01] 本次資料成功處理完畢
[2025-06-20 16:30:01] 本次資料成功處理完畢
[2025-06-20 16:31:01] 本次資料成功處理完畢
[2025-06-20 16:32:01] 本次資料成功處理完畢
[2025-06-20 16:33:01] 本次資料成功處理完畢
[2025-06-20 16:34:02] 本次資料成功處理完畢
[2025-06-20 16:35:01] 本次資料成功處理完畢
[2025-06-20 16:36:01] 本次資料成功處理完畢
[2025-06-20 16:37:01] 本次資料成功處理完畢
[2025-06-20 16:38:02] 本次資料成功處理完畢
[2025-06-20 16:39:01] 本次資料成功處理完畢
[2025-06-20 16:40:02] 本次資料成功處理完畢
[2025-06-20 16:41:02] 本次資料成功處理完畢
[2025-06-20 16:42:01] 本次資料成功處理完畢
[2025-06-20 16:43:01] 本次資料成功處理完畢
[2025-06-20 16:44:01] 本次資料成功處理完畢
[2025-06-20 16:45:01] 本次資料成功處理完畢
[2025-06-20 16:46:02] 本次資料成功處理完畢
[2025-06-20 16:47:01] 本次資料成功處理完畢
[2025-06-20 16:48:01] 本次資料成功處理完畢
[2025-06-20 16:49:01] 本次資料成功處理完畢
[2025-06-20 16:50:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 146B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.0s

#3 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/4] WORKDIR /app
#4 CACHED

#5 [internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 37.53kB done
#6 DONE 0.0s

#7 [3/4] RUN pip install requests psycopg2 SQLAlchemy pandas matplotlib numpy
#7 2.273 Collecting requests
#7 2.722   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#7 2.825      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 644.9 kB/s eta 0:00:00
#7 3.211 Collecting psycopg2
#7 3.386   Downloading psycopg2-2.9.10.tar.gz (385 kB)
#7 3.629      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 1.6 MB/s eta 0:00:00
#7 3.676   Preparing metadata (setup.py): started
#7 4.029   Preparing metadata (setup.py): finished with status 'done'
#7 5.396 Collecting SQLAlchemy
#7 5.532   Downloading sqlalchemy-2.0.41-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
#7 7.078      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 2.1 MB/s eta 0:00:00
#7 7.757 Collecting pandas
#7 7.859   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
#7 19.86      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 925.1 kB/s eta 0:00:00
#7 20.65 Collecting matplotlib
#7 20.82   Downloading matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
#7 29.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 1.0 MB/s eta 0:00:00
#7 30.66 Collecting numpy
#7 30.77   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#7 45.05      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 1.1 MB/s eta 0:00:00
#7 45.26 Collecting certifi>=2017.4.17
#7 45.39   Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
#7 45.49      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 1.5 MB/s eta 0:00:00
#7 45.61 Collecting idna<4,>=2.5
#7 45.70   Downloading idna-3.10-py3-none-any.whl (70 kB)
#7 45.73      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 3.4 MB/s eta 0:00:00
#7 46.06 Collecting charset_normalizer<4,>=2
#7 46.15   Downloading charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
#7 46.25      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 1.4 MB/s eta 0:00:00
#7 46.41 Collecting urllib3<3,>=1.21.1
#7 46.65   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#7 46.77      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 1.2 MB/s eta 0:00:00
#7 47.34 Collecting greenlet>=1
#7 47.44   Downloading greenlet-3.1.1-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (605 kB)
#7 47.96      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 606.0/606.0 kB 1.2 MB/s eta 0:00:00
#7 48.17 Collecting typing-extensions>=4.6.0
#7 48.29   Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
#7 48.35      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 609.9 kB/s eta 0:00:00
#7 48.66 Collecting pytz>=2020.1
#7 48.80   Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
#7 49.17      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 1.4 MB/s eta 0:00:00
#7 49.40 Collecting python-dateutil>=2.8.2
#7 49.48   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#7 49.63      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 1.6 MB/s eta 0:00:00
#7 49.73 Collecting tzdata>=2022.1
#7 49.88   Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
#7 50.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 1.1 MB/s eta 0:00:00
#7 50.42 Collecting pyparsing>=2.3.1
#7 50.51   Downloading pyparsing-3.1.4-py3-none-any.whl (104 kB)
#7 50.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 1.1 MB/s eta 0:00:00
#7 50.76 Collecting packaging>=20.0
#7 50.99   Downloading packaging-25.0-py3-none-any.whl (66 kB)
#7 51.02      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 13.6 MB/s eta 0:00:00
#7 51.63 Collecting pillow>=6.2.0
#7 51.80   Downloading pillow-10.4.0-cp38-cp38-manylinux_2_28_x86_64.whl (4.5 MB)
#7 56.21      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 1.0 MB/s eta 0:00:00
#7 56.41 Collecting importlib-resources>=3.2.0
#7 56.58   Downloading importlib_resources-6.4.5-py3-none-any.whl (36 kB)
#7 56.70 Collecting cycler>=0.10
#7 56.90   Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
#7 57.34 Collecting fonttools>=4.22.0
#7 57.44   Downloading fonttools-4.57.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
#7 62.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 883.5 kB/s eta 0:00:00
#7 63.16 Collecting contourpy>=1.0.1
#7 63.31   Downloading contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
#7 63.73      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.1/301.1 kB 781.3 kB/s eta 0:00:00
#7 64.06 Collecting kiwisolver>=1.0.1
#7 64.27   Downloading kiwisolver-1.4.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
#7 65.54      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 929.2 kB/s eta 0:00:00
#7 65.90 Collecting zipp>=3.1.0
#7 66.02   Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
#7 66.19 Collecting six>=1.5
#7 66.34   Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
#7 66.38 Building wheels for collected packages: psycopg2
#7 66.39   Building wheel for psycopg2 (setup.py): started
#7 73.25   Building wheel for psycopg2 (setup.py): finished with status 'done'
#7 73.25   Created wheel for psycopg2: filename=psycopg2-2.9.10-cp38-cp38-linux_x86_64.whl size=485118 sha256=9cacb7ec68eca6bcff81140ab1a0d22d21ea9cd25d6ebbffd4883da9778a8fae
#7 73.25   Stored in directory: /root/.cache/pip/wheels/85/b7/48/d6ffc48322fa70ef973e9ca95a5e012f2d71efadd88d847865
#7 73.26 Successfully built psycopg2
#7 73.51 Installing collected packages: pytz, zipp, urllib3, tzdata, typing-extensions, six, pyparsing, psycopg2, pillow, packaging, numpy, kiwisolver, idna, greenlet, fonttools, cycler, charset_normalizer, certifi, SQLAlchemy, requests, python-dateutil, importlib-resources, contourpy, pandas, matplotlib
#7 82.97 Successfully installed SQLAlchemy-2.0.41 certifi-2025.6.15 charset_normalizer-3.4.2 contourpy-1.1.1 cycler-0.12.1 fonttools-4.57.0 greenlet-3.1.1 idna-3.10 importlib-resources-6.4.5 kiwisolver-1.4.7 matplotlib-3.7.5 numpy-1.24.4 packaging-25.0 pandas-2.0.3 pillow-10.4.0 psycopg2-2.9.10 pyparsing-3.1.4 python-dateutil-2.9.0.post0 pytz-2025.2 requests-2.32.4 six-1.17.0 typing-extensions-4.13.2 tzdata-2025.2 urllib3-2.2.3 zipp-3.20.2
#7 82.97 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#7 83.31 
#7 83.31 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#7 83.31 [notice] To update, run: pip install --upgrade pip
#7 DONE 84.2s

#8 [4/4] COPY . .
#8 DONE 0.1s

#9 exporting to image
#9 exporting layers
#9 exporting layers 1.4s done
#9 writing image sha256:ba68c04377515abcf5747d5338f504bbd6e1f4c7179d0abe836b456c8c412186 0.0s done
#9 naming to docker.io/library/nutn-my-python done
#9 DONE 1.5s
本次資料成功處理完畢
[2025-06-20 16:51:01] 本次資料成功處理完畢
[2025-06-20 16:52:01] 本次資料成功處理完畢
[2025-06-20 16:53:04] 本次資料成功處理完畢
[2025-06-20 16:54:01] 本次資料成功處理完畢
[2025-06-20 16:55:02] 本次資料成功處理完畢
[2025-06-20 16:56:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 197B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [1/5] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/5] WORKDIR /app
#4 CACHED

#5 [3/5] RUN pip install requests psycopg2 SQLAlchemy pandas matplotlib numpy
#5 CACHED

#6 [internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [internal] load build context
#7 transferring context: 43.19kB done
#7 DONE 0.0s

#8 [4/5] RUN apt update && apt install -y fonts-noto-cjk
#8 0.245 
#8 0.245 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#8 0.245 
#8 0.675 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#8 0.946 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#8 1.036 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#8 1.285 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8793 kB]
#8 11.31 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [756 B]
#8 11.42 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [267 kB]
#8 12.13 Fetched 9315 kB in 12s (787 kB/s)
#8 12.13 Reading package lists...
#8 12.59 Building dependency tree...
#8 12.71 Reading state information...
#8 12.74 121 packages can be upgraded. Run 'apt list --upgradable' to see them.
#8 12.74 
#8 12.75 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#8 12.75 
#8 12.76 Reading package lists...
#8 13.24 Building dependency tree...
#8 13.36 Reading state information...
#8 13.51 Suggested packages:
#8 13.51   fonts-noto-cjk-extra
#8 13.55 The following NEW packages will be installed:
#8 13.55   fonts-noto-cjk
#8 13.80 0 upgraded, 1 newly installed, 0 to remove and 121 not upgraded.
#8 13.80 Need to get 56.5 MB of archives.
#8 13.80 After this operation, 93.2 MB of additional disk space will be used.
#8 13.80 Get:1 http://deb.debian.org/debian bookworm/main amd64 fonts-noto-cjk all 1:20220127+repack1-1 [56.5 MB]
#8 83.71 debconf: delaying package configuration, since apt-utils is not installed
#8 83.74 Fetched 56.5 MB in 1min 10s (809 kB/s)
#8 83.80 Selecting previously unselected package fonts-noto-cjk.
#8 83.80 (Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 23969 files and directories currently installed.)
#8 83.93 Preparing to unpack .../fonts-noto-cjk_1%3a20220127+repack1-1_all.deb ...
#8 84.09 Unpacking fonts-noto-cjk (1:20220127+repack1-1) ...
#8 88.16 Setting up fonts-noto-cjk (1:20220127+repack1-1) ...
#8 88.18 Processing triggers for fontconfig (2.14.1-4) ...
#8 DONE 88.5s

#9 [5/5] COPY . .
#9 DONE 0.1s

#10 exporting to image
#10 exporting layers
#10 exporting layers 0.3s done
#10 writing image sha256:520d661ab16e9ae020073261c170c6cba2b7865eae8338f7123f796f18c1dbb9 done
#10 naming to docker.io/library/nutn-my-python done
#10 DONE 0.3s
本次資料成功處理完畢
[2025-06-20 16:57:01] 本次資料成功處理完畢
[2025-06-20 16:58:04] 本次資料成功處理完畢
[2025-06-20 16:59:01] 本次資料成功處理完畢
[2025-06-20 17:00:01] 本次資料成功處理完畢
[2025-06-20 17:01:01] 本次資料成功處理完畢
[2025-06-20 17:02:02] 本次資料成功處理完畢
[2025-06-20 17:03:01] 本次資料成功處理完畢
[2025-06-20 17:04:02] 本次資料成功處理完畢
[2025-06-20 17:05:01] 本次資料成功處理完畢
[2025-06-20 17:06:01] 本次資料成功處理完畢
[2025-06-20 17:07:06] 本次資料成功處理完畢
[2025-06-20 17:08:01] Docker image nutn-my-python not found. Building...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 235B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.0s

#3 [1/5] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#3 DONE 0.0s

#4 [2/5] WORKDIR /app
#4 CACHED

#5 [3/5] RUN pip install requests psycopg2 SQLAlchemy pandas matplotlib numpy
#5 CACHED

#6 [internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [internal] load build context
#7 transferring context: 158.56kB 0.0s done
#7 DONE 0.0s

#8 [4/5] RUN apt-get update &&     apt-get install -y fonts-noto-cjk &&     fc-cache -f -v
#8 0.671 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#8 0.976 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#8 1.163 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#8 1.288 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8793 kB]
#8 3.941 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [756 B]
#8 4.167 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [267 kB]
#8 4.943 Fetched 9315 kB in 5s (1967 kB/s)
#8 4.943 Reading package lists...
#8 5.612 Reading package lists...
#8 6.163 Building dependency tree...
#8 6.326 Reading state information...
#8 6.549 Suggested packages:
#8 6.549   fonts-noto-cjk-extra
#8 6.588 The following NEW packages will be installed:
#8 6.589   fonts-noto-cjk
#8 6.795 0 upgraded, 1 newly installed, 0 to remove and 121 not upgraded.
#8 6.795 Need to get 56.5 MB of archives.
#8 6.795 After this operation, 93.2 MB of additional disk space will be used.
#8 6.795 Get:1 http://deb.debian.org/debian bookworm/main amd64 fonts-noto-cjk all 1:20220127+repack1-1 [56.5 MB]
#8 36.38 debconf: delaying package configuration, since apt-utils is not installed
#8 36.41 Fetched 56.5 MB in 30s (1909 kB/s)
#8 36.45 Selecting previously unselected package fonts-noto-cjk.
#8 36.45 (Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 23969 files and directories currently installed.)
#8 36.47 Preparing to unpack .../fonts-noto-cjk_1%3a20220127+repack1-1_all.deb ...
#8 36.48 Unpacking fonts-noto-cjk (1:20220127+repack1-1) ...
#8 38.07 Setting up fonts-noto-cjk (1:20220127+repack1-1) ...
#8 38.10 Processing triggers for fontconfig (2.14.1-4) ...
#8 38.21 Font directories:
#8 38.21 	/root/.local/share/fonts
#8 38.21 	/usr/local/share/fonts
#8 38.21 	/usr/share/fonts
#8 38.21 	/root/.fonts
#8 38.21 	/usr/share/fonts/opentype
#8 38.21 	/usr/share/fonts/truetype
#8 38.21 	/usr/share/fonts/opentype/noto
#8 38.21 	/usr/share/fonts/truetype/dejavu
#8 38.21 /root/.local/share/fonts: skipping, no such directory
#8 38.21 /usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
#8 38.21 /usr/share/fonts: caching, new cache contents: 0 fonts, 2 dirs
#8 38.21 /usr/share/fonts/opentype: caching, new cache contents: 0 fonts, 1 dirs
#8 38.21 /usr/share/fonts/opentype/noto: caching, new cache contents: 30 fonts, 0 dirs
#8 38.26 /usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 1 dirs
#8 38.26 /usr/share/fonts/truetype/dejavu: caching, new cache contents: 6 fonts, 0 dirs
#8 38.26 /root/.fonts: skipping, no such directory
#8 38.26 /usr/share/fonts/opentype: skipping, looped directory detected
#8 38.26 /usr/share/fonts/truetype: skipping, looped directory detected
#8 38.26 /usr/share/fonts/opentype/noto: skipping, looped directory detected
#8 38.26 /usr/share/fonts/truetype/dejavu: skipping, looped directory detected
#8 40.28 /var/cache/fontconfig: cleaning cache directory
#8 40.28 /root/.cache/fontconfig: not cleaning non-existent cache directory
#8 40.28 /root/.fontconfig: not cleaning non-existent cache directory
#8 40.28 fc-cache: succeeded
#8 DONE 40.5s

#9 [5/5] COPY . .
#9 DONE 0.1s

#10 exporting to image
#10 exporting layers
#10 exporting layers 0.2s done
#10 writing image sha256:4fec13378137eff10620684aa652b5daaf631691a3008d20742acbdf949b19a1
#10 writing image sha256:4fec13378137eff10620684aa652b5daaf631691a3008d20742acbdf949b19a1 0.0s done
#10 naming to docker.io/library/nutn-my-python done
#10 DONE 0.3s
本次資料成功處理完畢
[2025-06-20 17:09:01] 本次資料成功處理完畢
[2025-06-20 17:10:02] 本次資料成功處理完畢
[2025-06-20 17:11:02] 本次資料成功處理完畢
[2025-06-20 17:12:01] 本次資料成功處理完畢
[2025-06-20 17:13:01] 本次資料成功處理完畢
[2025-06-20 17:14:01] 本次資料成功處理完畢
[2025-06-20 17:15:01] 本次資料成功處理完畢
[2025-06-20 17:16:03] 本次資料成功處理完畢
[2025-06-20 17:17:02] 本次資料成功處理完畢
[2025-06-20 17:18:01] 本次資料成功處理完畢
[2025-06-20 17:19:01] 本次資料成功處理完畢
[2025-06-20 17:20:13] 本次資料成功處理完畢
[2025-06-20 17:21:01] 本次資料成功處理完畢
[2025-06-20 17:22:01] 本次資料成功處理完畢
[2025-06-20 17:23:01] 本次資料成功處理完畢
[2025-06-20 17:24:01] 本次資料成功處理完畢
[2025-06-20 17:25:01] 本次資料成功處理完畢
[2025-06-20 17:26:02] 本次資料成功處理完畢
[2025-06-20 17:27:01] 本次資料成功處理完畢
[2025-06-20 17:28:01] 本次資料成功處理完畢
[2025-06-20 17:29:01] 本次資料成功處理完畢
[2025-06-20 17:30:01] 本次資料成功處理完畢
[2025-06-20 17:31:01] 本次資料成功處理完畢
[2025-06-20 17:32:01] 本次資料成功處理完畢
[2025-06-20 17:33:01] 本次資料成功處理完畢
[2025-06-20 17:34:01] 本次資料成功處理完畢
[2025-06-20 17:35:03] 本次資料成功處理完畢
[2025-06-20 17:36:02] 本次資料成功處理完畢
[2025-06-20 17:37:01] 本次資料成功處理完畢
[2025-06-20 17:38:01] 本次資料成功處理完畢
[2025-06-20 17:39:04] 本次資料成功處理完畢
[2025-06-20 17:40:02] 本次資料成功處理完畢
[2025-06-20 17:41:02] 本次資料成功處理完畢
[2025-06-20 17:42:01] 本次資料成功處理完畢
[2025-06-20 17:43:04] 本次資料成功處理完畢
[2025-06-20 17:44:01] 本次資料成功處理完畢
[2025-06-20 17:45:02] 本次資料成功處理完畢
[2025-06-20 17:46:01] 本次資料成功處理完畢
[2025-06-20 17:47:01] ⚠️ 資料插入失敗（站點 500101001）: 'lat'
⚠️ 資料插入失敗（站點 500101002）: 'lat'
⚠️ 資料插入失敗（站點 500101003）: 'lat'
⚠️ 資料插入失敗（站點 500101004）: 'lat'
⚠️ 資料插入失敗（站點 500101005）: 'lat'
⚠️ 資料插入失敗（站點 500101006）: 'lat'
⚠️ 資料插入失敗（站點 500101007）: 'lat'
⚠️ 資料插入失敗（站點 500101008）: 'lat'
⚠️ 資料插入失敗（站點 500101009）: 'lat'
⚠️ 資料插入失敗（站點 500101010）: 'lat'
⚠️ 資料插入失敗（站點 500101012）: 'lat'
⚠️ 資料插入失敗（站點 500101013）: 'lat'
⚠️ 資料插入失敗（站點 500101014）: 'lat'
⚠️ 資料插入失敗（站點 500101015）: 'lat'
⚠️ 資料插入失敗（站點 500101016）: 'lat'
⚠️ 資料插入失敗（站點 500101018）: 'lat'
⚠️ 資料插入失敗（站點 500101019）: 'lat'
⚠️ 資料插入失敗（站點 500101020）: 'lat'
⚠️ 資料插入失敗（站點 500101021）: 'lat'
⚠️ 資料插入失敗（站點 500101022）: 'lat'
⚠️ 資料插入失敗（站點 500101023）: 'lat'
⚠️ 資料插入失敗（站點 500101024）: 'lat'
⚠️ 資料插入失敗（站點 500101025）: 'lat'
⚠️ 資料插入失敗（站點 500101026）: 'lat'
⚠️ 資料插入失敗（站點 500101027）: 'lat'
⚠️ 資料插入失敗（站點 500101028）: 'lat'
⚠️ 資料插入失敗（站點 500101029）: 'lat'
⚠️ 資料插入失敗（站點 500101030）: 'lat'
⚠️ 資料插入失敗（站點 500101031）: 'lat'
⚠️ 資料插入失敗（站點 500101032）: 'lat'
⚠️ 資料插入失敗（站點 500101033）: 'lat'
⚠️ 資料插入失敗（站點 500101034）: 'lat'
⚠️ 資料插入失敗（站點 500101035）: 'lat'
⚠️ 資料插入失敗（站點 500101036）: 'lat'
⚠️ 資料插入失敗（站點 500101037）: 'lat'
⚠️ 資料插入失敗（站點 500101038）: 'lat'
⚠️ 資料插入失敗（站點 500101039）: 'lat'
⚠️ 資料插入失敗（站點 500101040）: 'lat'
⚠️ 資料插入失敗（站點 500101041）: 'lat'
⚠️ 資料插入失敗（站點 500101042）: 'lat'
⚠️ 資料插入失敗（站點 500101091）: 'lat'
⚠️ 資料插入失敗（站點 500101092）: 'lat'
⚠️ 資料插入失敗（站點 500101093）: 'lat'
⚠️ 資料插入失敗（站點 500101094）: 'lat'
⚠️ 資料插入失敗（站點 500101095）: 'lat'
⚠️ 資料插入失敗（站點 500101097）: 'lat'
⚠️ 資料插入失敗（站點 500101098）: 'lat'
⚠️ 資料插入失敗（站點 500101099）: 'lat'
⚠️ 資料插入失敗（站點 500101100）: 'lat'
⚠️ 資料插入失敗（站點 500101101）: 'lat'
⚠️ 資料插入失敗（站點 500101102）: 'lat'
⚠️ 資料插入失敗（站點 500101103）: 'lat'
⚠️ 資料插入失敗（站點 500101104）: 'lat'
⚠️ 資料插入失敗（站點 500101105）: 'lat'
⚠️ 資料插入失敗（站點 500101107）: 'lat'
⚠️ 資料插入失敗（站點 500101108）: 'lat'
⚠️ 資料插入失敗（站點 500101109）: 'lat'
⚠️ 資料插入失敗（站點 500101110）: 'lat'
⚠️ 資料插入失敗（站點 500101111）: 'lat'
⚠️ 資料插入失敗（站點 500101113）: 'lat'
⚠️ 資料插入失敗（站點 500101114）: 'lat'
⚠️ 資料插入失敗（站點 500101115）: 'lat'
⚠️ 資料插入失敗（站點 500101116）: 'lat'
⚠️ 資料插入失敗（站點 500101117）: 'lat'
⚠️ 資料插入失敗（站點 500101118）: 'lat'
⚠️ 資料插入失敗（站點 500101119）: 'lat'
⚠️ 資料插入失敗（站點 500101120）: 'lat'
⚠️ 資料插入失敗（站點 500101122）: 'lat'
⚠️ 資料插入失敗（站點 500101123）: 'lat'
⚠️ 資料插入失敗（站點 500101124）: 'lat'
⚠️ 資料插入失敗（站點 500101125）: 'lat'
⚠️ 資料插入失敗（站點 500101126）: 'lat'
⚠️ 資料插入失敗（站點 500101127）: 'lat'
⚠️ 資料插入失敗（站點 500101128）: 'lat'
⚠️ 資料插入失敗（站點 500101129）: 'lat'
⚠️ 資料插入失敗（站點 500101130）: 'lat'
⚠️ 資料插入失敗（站點 500101131）: 'lat'
⚠️ 資料插入失敗（站點 500101132）: 'lat'
⚠️ 資料插入失敗（站點 500101133）: 'lat'
⚠️ 資料插入失敗（站點 500101134）: 'lat'
⚠️ 資料插入失敗（站點 500101135）: 'lat'
⚠️ 資料插入失敗（站點 500101136）: 'lat'
⚠️ 資料插入失敗（站點 500101137）: 'lat'
⚠️ 資料插入失敗（站點 500101138）: 'lat'
⚠️ 資料插入失敗（站點 500101139）: 'lat'
⚠️ 資料插入失敗（站點 500101140）: 'lat'
⚠️ 資料插入失敗（站點 500101141）: 'lat'
⚠️ 資料插入失敗（站點 500101142）: 'lat'
⚠️ 資料插入失敗（站點 500101143）: 'lat'
⚠️ 資料插入失敗（站點 500101144）: 'lat'
⚠️ 資料插入失敗（站點 500101145）: 'lat'
⚠️ 資料插入失敗（站點 500101146）: 'lat'
⚠️ 資料插入失敗（站點 500101147）: 'lat'
⚠️ 資料插入失敗（站點 500101148）: 'lat'
⚠️ 資料插入失敗（站點 500101149）: 'lat'
⚠️ 資料插入失敗（站點 500101150）: 'lat'
⚠️ 資料插入失敗（站點 500101151）: 'lat'
⚠️ 資料插入失敗（站點 500101152）: 'lat'
⚠️ 資料插入失敗（站點 500101153）: 'lat'
⚠️ 資料插入失敗（站點 500101154）: 'lat'
⚠️ 資料插入失敗（站點 500101155）: 'lat'
⚠️ 資料插入失敗（站點 500101156）: 'lat'
⚠️ 資料插入失敗（站點 500101157）: 'lat'
⚠️ 資料插入失敗（站點 500101158）: 'lat'
⚠️ 資料插入失敗（站點 500101159）: 'lat'
⚠️ 資料插入失敗（站點 500101160）: 'lat'
⚠️ 資料插入失敗（站點 500101161）: 'lat'
⚠️ 資料插入失敗（站點 500101162）: 'lat'
⚠️ 資料插入失敗（站點 500101163）: 'lat'
⚠️ 資料插入失敗（站點 500101165）: 'lat'
⚠️ 資料插入失敗（站點 500101166）: 'lat'
⚠️ 資料插入失敗（站點 500101167）: 'lat'
⚠️ 資料插入失敗（站點 500101168）: 'lat'
⚠️ 資料插入失敗（站點 500101169）: 'lat'
⚠️ 資料插入失敗（站點 500101170）: 'lat'
⚠️ 資料插入失敗（站點 500101171）: 'lat'
⚠️ 資料插入失敗（站點 500101172）: 'lat'
⚠️ 資料插入失敗（站點 500101173）: 'lat'
⚠️ 資料插入失敗（站點 500101174）: 'lat'
⚠️ 資料插入失敗（站點 500101175）: 'lat'
⚠️ 資料插入失敗（站點 500101176）: 'lat'
⚠️ 資料插入失敗（站點 500101177）: 'lat'
⚠️ 資料插入失敗（站點 500101179）: 'lat'
⚠️ 資料插入失敗（站點 500101180）: 'lat'
⚠️ 資料插入失敗（站點 500101181）: 'lat'
⚠️ 資料插入失敗（站點 500101182）: 'lat'
⚠️ 資料插入失敗（站點 500101184）: 'lat'
⚠️ 資料插入失敗（站點 500101185）: 'lat'
⚠️ 資料插入失敗（站點 500101186）: 'lat'
⚠️ 資料插入失敗（站點 500101187）: 'lat'
⚠️ 資料插入失敗（站點 500101188）: 'lat'
⚠️ 資料插入失敗（站點 500101189）: 'lat'
⚠️ 資料插入失敗（站點 500101190）: 'lat'
⚠️ 資料插入失敗（站點 500101191）: 'lat'
⚠️ 資料插入失敗（站點 500101192）: 'lat'
⚠️ 資料插入失敗（站點 500101193）: 'lat'
⚠️ 資料插入失敗（站點 500101194）: 'lat'
⚠️ 資料插入失敗（站點 500101196）: 'lat'
⚠️ 資料插入失敗（站點 500101197）: 'lat'
⚠️ 資料插入失敗（站點 500101198）: 'lat'
⚠️ 資料插入失敗（站點 500101199）: 'lat'
⚠️ 資料插入失敗（站點 500101200）: 'lat'
⚠️ 資料插入失敗（站點 500101201）: 'lat'
⚠️ 資料插入失敗（站點 500101202）: 'lat'
⚠️ 資料插入失敗（站點 500101203）: 'lat'
⚠️ 資料插入失敗（站點 500101204）: 'lat'
⚠️ 資料插入失敗（站點 500101205）: 'lat'
⚠️ 資料插入失敗（站點 500101206）: 'lat'
⚠️ 資料插入失敗（站點 500101207）: 'lat'
⚠️ 資料插入失敗（站點 500101208）: 'lat'
⚠️ 資料插入失敗（站點 500101209）: 'lat'
⚠️ 資料插入失敗（站點 500101210）: 'lat'
⚠️ 資料插入失敗（站點 500101211）: 'lat'
⚠️ 資料插入失敗（站點 500101212）: 'lat'
⚠️ 資料插入失敗（站點 500101213）: 'lat'
⚠️ 資料插入失敗（站點 500101214）: 'lat'
⚠️ 資料插入失敗（站點 500101215）: 'lat'
⚠️ 資料插入失敗（站點 500101216）: 'lat'
⚠️ 資料插入失敗（站點 500101217）: 'lat'
⚠️ 資料插入失敗（站點 500101218）: 'lat'
⚠️ 資料插入失敗（站點 500101219）: 'lat'
⚠️ 資料插入失敗（站點 500101221）: 'lat'
⚠️ 資料插入失敗（站點 500101222）: 'lat'
⚠️ 資料插入失敗（站點 500101223）: 'lat'
⚠️ 資料插入失敗（站點 500101224）: 'lat'
⚠️ 資料插入失敗（站點 500101225）: 'lat'
⚠️ 資料插入失敗（站點 500101226）: 'lat'
⚠️ 資料插入失敗（站點 500101227）: 'lat'
⚠️ 資料插入失敗（站點 500101228）: 'lat'
⚠️ 資料插入失敗（站點 500101229）: 'lat'
⚠️ 資料插入失敗（站點 500101230）: 'lat'
⚠️ 資料插入失敗（站點 500101231）: 'lat'
⚠️ 資料插入失敗（站點 500101232）: 'lat'
⚠️ 資料插入失敗（站點 500101233）: 'lat'
⚠️ 資料插入失敗（站點 500101234）: 'lat'
⚠️ 資料插入失敗（站點 500101235）: 'lat'
⚠️ 資料插入失敗（站點 500101236）: 'lat'
⚠️ 資料插入失敗（站點 500101237）: 'lat'
⚠️ 資料插入失敗（站點 500101238）: 'lat'
⚠️ 資料插入失敗（站點 500101239）: 'lat'
⚠️ 資料插入失敗（站點 500101240）: 'lat'
⚠️ 資料插入失敗（站點 500101241）: 'lat'
⚠️ 資料插入失敗（站點 500101242）: 'lat'
⚠️ 資料插入失敗（站點 500101243）: 'lat'
⚠️ 資料插入失敗（站點 500101244）: 'lat'
⚠️ 資料插入失敗（站點 500101245）: 'lat'
⚠️ 資料插入失敗（站點 500101246）: 'lat'
⚠️ 資料插入失敗（站點 500101247）: 'lat'
⚠️ 資料插入失敗（站點 500101248）: 'lat'
⚠️ 資料插入失敗（站點 500101250）: 'lat'
⚠️ 資料插入失敗（站點 500101251）: 'lat'
⚠️ 資料插入失敗（站點 500101252）: 'lat'
⚠️ 資料插入失敗（站點 500101253）: 'lat'
⚠️ 資料插入失敗（站點 500101254）: 'lat'
⚠️ 資料插入失敗（站點 500101256）: 'lat'
⚠️ 資料插入失敗（站點 500101257）: 'lat'
⚠️ 資料插入失敗（站點 500101258）: 'lat'
⚠️ 資料插入失敗（站點 500101259）: 'lat'
⚠️ 資料插入失敗（站點 500101260）: 'lat'
⚠️ 資料插入失敗（站點 500103001）: 'lat'
⚠️ 資料插入失敗（站點 500103002）: 'lat'
⚠️ 資料插入失敗（站點 500103003）: 'lat'
⚠️ 資料插入失敗（站點 500103004）: 'lat'
⚠️ 資料插入失敗（站點 500103005）: 'lat'
⚠️ 資料插入失敗（站點 500103006）: 'lat'
⚠️ 資料插入失敗（站點 500103007）: 'lat'
⚠️ 資料插入失敗（站點 500103008）: 'lat'
⚠️ 資料插入失敗（站點 500103009）: 'lat'
⚠️ 資料插入失敗（站點 500103010）: 'lat'
⚠️ 資料插入失敗（站點 500103011）: 'lat'
⚠️ 資料插入失敗（站點 500103012）: 'lat'
⚠️ 資料插入失敗（站點 500103013）: 'lat'
⚠️ 資料插入失敗（站點 500103019）: 'lat'
⚠️ 資料插入失敗（站點 500103020）: 'lat'
⚠️ 資料插入失敗（站點 500103021）: 'lat'
⚠️ 資料插入失敗（站點 500103022）: 'lat'
⚠️ 資料插入失敗（站點 500103023）: 'lat'
⚠️ 資料插入失敗（站點 500103024）: 'lat'
⚠️ 資料插入失敗（站點 500103025）: 'lat'
⚠️ 資料插入失敗（站點 500103026）: 'lat'
⚠️ 資料插入失敗（站點 500103027）: 'lat'
⚠️ 資料插入失敗（站點 500103028）: 'lat'
⚠️ 資料插入失敗（站點 500103029）: 'lat'
⚠️ 資料插入失敗（站點 500103030）: 'lat'
⚠️ 資料插入失敗（站點 500103031）: 'lat'
⚠️ 資料插入失敗（站點 500103032）: 'lat'
⚠️ 資料插入失敗（站點 500103033）: 'lat'
⚠️ 資料插入失敗（站點 500103034）: 'lat'
⚠️ 資料插入失敗（站點 500103035）: 'lat'
⚠️ 資料插入失敗（站點 500103036）: 'lat'
⚠️ 資料插入失敗（站點 500103037）: 'lat'
⚠️ 資料插入失敗（站點 500103038）: 'lat'
⚠️ 資料插入失敗（站點 500103039）: 'lat'
⚠️ 資料插入失敗（站點 500103040）: 'lat'
⚠️ 資料插入失敗（站點 500103041）: 'lat'
⚠️ 資料插入失敗（站點 500103042）: 'lat'
⚠️ 資料插入失敗（站點 500103043）: 'lat'
⚠️ 資料插入失敗（站點 500103044）: 'lat'
⚠️ 資料插入失敗（站點 500103045）: 'lat'
⚠️ 資料插入失敗（站點 500103046）: 'lat'
⚠️ 資料插入失敗（站點 500103047）: 'lat'
⚠️ 資料插入失敗（站點 500103048）: 'lat'
⚠️ 資料插入失敗（站點 500103049）: 'lat'
⚠️ 資料插入失敗（站點 500103050）: 'lat'
⚠️ 資料插入失敗（站點 500103051）: 'lat'
⚠️ 資料插入失敗（站點 500103052）: 'lat'
⚠️ 資料插入失敗（站點 500103053）: 'lat'
⚠️ 資料插入失敗（站點 500103054）: 'lat'
⚠️ 資料插入失敗（站點 500103055）: 'lat'
⚠️ 資料插入失敗（站點 500103056）: 'lat'
⚠️ 資料插入失敗（站點 500103057）: 'lat'
⚠️ 資料插入失敗（站點 500103058）: 'lat'
⚠️ 資料插入失敗（站點 500103059）: 'lat'
⚠️ 資料插入失敗（站點 500103060）: 'lat'
⚠️ 資料插入失敗（站點 500103061）: 'lat'
⚠️ 資料插入失敗（站點 500103062）: 'lat'
⚠️ 資料插入失敗（站點 500103063）: 'lat'
⚠️ 資料插入失敗（站點 500103064）: 'lat'
⚠️ 資料插入失敗（站點 500103065）: 'lat'
⚠️ 資料插入失敗（站點 500103066）: 'lat'
⚠️ 資料插入失敗（站點 500103068）: 'lat'
⚠️ 資料插入失敗（站點 500103069）: 'lat'
⚠️ 資料插入失敗（站點 500103070）: 'lat'
⚠️ 資料插入失敗（站點 500103071）: 'lat'
⚠️ 資料插入失敗（站點 500103072）: 'lat'
⚠️ 資料插入失敗（站點 500103073）: 'lat'
⚠️ 資料插入失敗（站點 500103074）: 'lat'
⚠️ 資料插入失敗（站點 500103075）: 'lat'
⚠️ 資料插入失敗（站點 500103076）: 'lat'
⚠️ 資料插入失敗（站點 500103077）: 'lat'
⚠️ 資料插入失敗（站點 500103078）: 'lat'
⚠️ 資料插入失敗（站點 500103079）: 'lat'
⚠️ 資料插入失敗（站點 500104001）: 'lat'
⚠️ 資料插入失敗（站點 500104002）: 'lat'
⚠️ 資料插入失敗（站點 500104003）: 'lat'
⚠️ 資料插入失敗（站點 500104004）: 'lat'
⚠️ 資料插入失敗（站點 500104005）: 'lat'
⚠️ 資料插入失敗（站點 500104006）: 'lat'
⚠️ 資料插入失敗（站點 500104007）: 'lat'
⚠️ 資料插入失敗（站點 500104008）: 'lat'
⚠️ 資料插入失敗（站點 500104009）: 'lat'
⚠️ 資料插入失敗（站點 500104010）: 'lat'
⚠️ 資料插入失敗（站點 500104012）: 'lat'
⚠️ 資料插入失敗（站點 500104013）: 'lat'
⚠️ 資料插入失敗（站點 500104014）: 'lat'
⚠️ 資料插入失敗（站點 500104015）: 'lat'
⚠️ 資料插入失敗（站點 500104016）: 'lat'
⚠️ 資料插入失敗（站點 500104018）: 'lat'
⚠️ 資料插入失敗（站點 500104019）: 'lat'
⚠️ 資料插入失敗（站點 500104020）: 'lat'
⚠️ 資料插入失敗（站點 500104021）: 'lat'
⚠️ 資料插入失敗（站點 500104022）: 'lat'
⚠️ 資料插入失敗（站點 500104023）: 'lat'
⚠️ 資料插入失敗（站點 500104024）: 'lat'
⚠️ 資料插入失敗（站點 500104025）: 'lat'
⚠️ 資料插入失敗（站點 500104026）: 'lat'
⚠️ 資料插入失敗（站點 500104027）: 'lat'
⚠️ 資料插入失敗（站點 500104028）: 'lat'
⚠️ 資料插入失敗（站點 500104029）: 'lat'
⚠️ 資料插入失敗（站點 500104030）: 'lat'
⚠️ 資料插入失敗（站點 500104031）: 'lat'
⚠️ 資料插入失敗（站點 500104032）: 'lat'
⚠️ 資料插入失敗（站點 500104033）: 'lat'
⚠️ 資料插入失敗（站點 500104034）: 'lat'
⚠️ 資料插入失敗（站點 500104035）: 'lat'
⚠️ 資料插入失敗（站點 500104036）: 'lat'
⚠️ 資料插入失敗（站點 500104037）: 'lat'
⚠️ 資料插入失敗（站點 500104038）: 'lat'
⚠️ 資料插入失敗（站點 500104039）: 'lat'
⚠️ 資料插入失敗（站點 500104040）: 'lat'
⚠️ 資料插入失敗（站點 500104041）: 'lat'
⚠️ 資料插入失敗（站點 500104042）: 'lat'
⚠️ 資料插入失敗（站點 500104043）: 'lat'
⚠️ 資料插入失敗（站點 500104044）: 'lat'
⚠️ 資料插入失敗（站點 500104045）: 'lat'
⚠️ 資料插入失敗（站點 500104046）: 'lat'
⚠️ 資料插入失敗（站點 500104047）: 'lat'
⚠️ 資料插入失敗（站點 500104048）: 'lat'
⚠️ 資料插入失敗（站點 500104049）: 'lat'
⚠️ 資料插入失敗（站點 500104050）: 'lat'
⚠️ 資料插入失敗（站點 500104051）: 'lat'
⚠️ 資料插入失敗（站點 500104052）: 'lat'
⚠️ 資料插入失敗（站點 500104053）: 'lat'
⚠️ 資料插入失敗（站點 500104054）: 'lat'
⚠️ 資料插入失敗（站點 500104055）: 'lat'
⚠️ 資料插入失敗（站點 500104056）: 'lat'
⚠️ 資料插入失敗（站點 500104057）: 'lat'
⚠️ 資料插入失敗（站點 500104058）: 'lat'
⚠️ 資料插入失敗（站點 500104059）: 'lat'
⚠️ 資料插入失敗（站點 500104060）: 'lat'
⚠️ 資料插入失敗（站點 500104061）: 'lat'
⚠️ 資料插入失敗（站點 500104062）: 'lat'
⚠️ 資料插入失敗（站點 500104063）: 'lat'
⚠️ 資料插入失敗（站點 500104064）: 'lat'
⚠️ 資料插入失敗（站點 500104065）: 'lat'
⚠️ 資料插入失敗（站點 500104066）: 'lat'
⚠️ 資料插入失敗（站點 500104067）: 'lat'
⚠️ 資料插入失敗（站點 500104068）: 'lat'
⚠️ 資料插入失敗（站點 500104069）: 'lat'
⚠️ 資料插入失敗（站點 500104070）: 'lat'
⚠️ 資料插入失敗（站點 500104071）: 'lat'
⚠️ 資料插入失敗（站點 500104072）: 'lat'
⚠️ 資料插入失敗（站點 500104073）: 'lat'
⚠️ 資料插入失敗（站點 500104074）: 'lat'
⚠️ 資料插入失敗（站點 500104075）: 'lat'
⚠️ 資料插入失敗（站點 500104076）: 'lat'
⚠️ 資料插入失敗（站點 500104077）: 'lat'
⚠️ 資料插入失敗（站點 500104078）: 'lat'
⚠️ 資料插入失敗（站點 500104079）: 'lat'
⚠️ 資料插入失敗（站點 500104080）: 'lat'
⚠️ 資料插入失敗（站點 500104081）: 'lat'
⚠️ 資料插入失敗（站點 500104082）: 'lat'
⚠️ 資料插入失敗（站點 500104083）: 'lat'
⚠️ 資料插入失敗（站點 500104084）: 'lat'
⚠️ 資料插入失敗（站點 500104085）: 'lat'
⚠️ 資料插入失敗（站點 500104086）: 'lat'
⚠️ 資料插入失敗（站點 500104087）: 'lat'
⚠️ 資料插入失敗（站點 500104088）: 'lat'
⚠️ 資料插入失敗（站點 500104089）: 'lat'
⚠️ 資料插入失敗（站點 500104090）: 'lat'
⚠️ 資料插入失敗（站點 500104091）: 'lat'
⚠️ 資料插入失敗（站點 500104092）: 'lat'
⚠️ 資料插入失敗（站點 500104094）: 'lat'
⚠️ 資料插入失敗（站點 500104095）: 'lat'
⚠️ 資料插入失敗（站點 500104096）: 'lat'
⚠️ 資料插入失敗（站點 500104097）: 'lat'
⚠️ 資料插入失敗（站點 500104098）: 'lat'
⚠️ 資料插入失敗（站點 500104099）: 'lat'
⚠️ 資料插入失敗（站點 500104100）: 'lat'
⚠️ 資料插入失敗（站點 500104101）: 'lat'
⚠️ 資料插入失敗（站點 500104102）: 'lat'
⚠️ 資料插入失敗（站點 500104103）: 'lat'
⚠️ 資料插入失敗（站點 500104104）: 'lat'
⚠️ 資料插入失敗（站點 500104105）: 'lat'
⚠️ 資料插入失敗（站點 500104106）: 'lat'
⚠️ 資料插入失敗（站點 500104107）: 'lat'
⚠️ 資料插入失敗（站點 500104108）: 'lat'
⚠️ 資料插入失敗（站點 500104109）: 'lat'
⚠️ 資料插入失敗（站點 500104110）: 'lat'
⚠️ 資料插入失敗（站點 500104111）: 'lat'
⚠️ 資料插入失敗（站點 500104112）: 'lat'
⚠️ 資料插入失敗（站點 500104113）: 'lat'
⚠️ 資料插入失敗（站點 500104114）: 'lat'
⚠️ 資料插入失敗（站點 500104115）: 'lat'
⚠️ 資料插入失敗（站點 500104116）: 'lat'
⚠️ 資料插入失敗（站點 500104117）: 'lat'
⚠️ 資料插入失敗（站點 500104118）: 'lat'
⚠️ 資料插入失敗（站點 500104119）: 'lat'
⚠️ 資料插入失敗（站點 500104120）: 'lat'
⚠️ 資料插入失敗（站點 500104121）: 'lat'
⚠️ 資料插入失敗（站點 500104122）: 'lat'
⚠️ 資料插入失敗（站點 500104123）: 'lat'
⚠️ 資料插入失敗（站點 500104124）: 'lat'
⚠️ 資料插入失敗（站點 500104125）: 'lat'
⚠️ 資料插入失敗（站點 500104126）: 'lat'
⚠️ 資料插入失敗（站點 500104128）: 'lat'
⚠️ 資料插入失敗（站點 500104129）: 'lat'
⚠️ 資料插入失敗（站點 500104130）: 'lat'
⚠️ 資料插入失敗（站點 500104131）: 'lat'
⚠️ 資料插入失敗（站點 500104132）: 'lat'
⚠️ 資料插入失敗（站點 500104133）: 'lat'
⚠️ 資料插入失敗（站點 500104134）: 'lat'
⚠️ 資料插入失敗（站點 500104135）: 'lat'
⚠️ 資料插入失敗（站點 500104136）: 'lat'
⚠️ 資料插入失敗（站點 500104137）: 'lat'
⚠️ 資料插入失敗（站點 500104138）: 'lat'
⚠️ 資料插入失敗（站點 500104139）: 'lat'
⚠️ 資料插入失敗（站點 500104140）: 'lat'
⚠️ 資料插入失敗（站點 500105001）: 'lat'
⚠️ 資料插入失敗（站點 500105002）: 'lat'
⚠️ 資料插入失敗（站點 500105003）: 'lat'
⚠️ 資料插入失敗（站點 500105004）: 'lat'
⚠️ 資料插入失敗（站點 500105005）: 'lat'
⚠️ 資料插入失敗（站點 500105006）: 'lat'
⚠️ 資料插入失敗（站點 500105007）: 'lat'
⚠️ 資料插入失敗（站點 500105008）: 'lat'
⚠️ 資料插入失敗（站點 500105009）: 'lat'
⚠️ 資料插入失敗（站點 500105010）: 'lat'
⚠️ 資料插入失敗（站點 500105011）: 'lat'
⚠️ 資料插入失敗（站點 500105012）: 'lat'
⚠️ 資料插入失敗（站點 500105013）: 'lat'
⚠️ 資料插入失敗（站點 500105014）: 'lat'
⚠️ 資料插入失敗（站點 500105015）: 'lat'
⚠️ 資料插入失敗（站點 500105016）: 'lat'
⚠️ 資料插入失敗（站點 500105017）: 'lat'
⚠️ 資料插入失敗（站點 500105018）: 'lat'
⚠️ 資料插入失敗（站點 500105019）: 'lat'
⚠️ 資料插入失敗（站點 500105020）: 'lat'
⚠️ 資料插入失敗（站點 500105021）: 'lat'
⚠️ 資料插入失敗（站點 500105022）: 'lat'
⚠️ 資料插入失敗（站點 500105023）: 'lat'
⚠️ 資料插入失敗（站點 500105024）: 'lat'
⚠️ 資料插入失敗（站點 500105025）: 'lat'
⚠️ 資料插入失敗（站點 500105026）: 'lat'
⚠️ 資料插入失敗（站點 500105027）: 'lat'
⚠️ 資料插入失敗（站點 500105028）: 'lat'
⚠️ 資料插入失敗（站點 500105029）: 'lat'
⚠️ 資料插入失敗（站點 500105030）: 'lat'
⚠️ 資料插入失敗（站點 500105031）: 'lat'
⚠️ 資料插入失敗（站點 500105032）: 'lat'
⚠️ 資料插入失敗（站點 500105033）: 'lat'
⚠️ 資料插入失敗（站點 500105034）: 'lat'
⚠️ 資料插入失敗（站點 500105035）: 'lat'
⚠️ 資料插入失敗（站點 500105036）: 'lat'
⚠️ 資料插入失敗（站點 500105037）: 'lat'
⚠️ 資料插入失敗（站點 500105038）: 'lat'
⚠️ 資料插入失敗（站點 500105039）: 'lat'
⚠️ 資料插入失敗（站點 500105040）: 'lat'
⚠️ 資料插入失敗（站點 500105041）: 'lat'
⚠️ 資料插入失敗（站點 500105042）: 'lat'
⚠️ 資料插入失敗（站點 500105043）: 'lat'
⚠️ 資料插入失敗（站點 500105044）: 'lat'
⚠️ 資料插入失敗（站點 500105045）: 'lat'
⚠️ 資料插入失敗（站點 500105046）: 'lat'
⚠️ 資料插入失敗（站點 500105047）: 'lat'
⚠️ 資料插入失敗（站點 500105048）: 'lat'
⚠️ 資料插入失敗（站點 500105049）: 'lat'
⚠️ 資料插入失敗（站點 500105050）: 'lat'
⚠️ 資料插入失敗（站點 500105051）: 'lat'
⚠️ 資料插入失敗（站點 500105053）: 'lat'
⚠️ 資料插入失敗（站點 500105054）: 'lat'
⚠️ 資料插入失敗（站點 500105055）: 'lat'
⚠️ 資料插入失敗（站點 500105056）: 'lat'
⚠️ 資料插入失敗（站點 500105057）: 'lat'
⚠️ 資料插入失敗（站點 500105058）: 'lat'
⚠️ 資料插入失敗（站點 500105059）: 'lat'
⚠️ 資料插入失敗（站點 500105060）: 'lat'
⚠️ 資料插入失敗（站點 500105061）: 'lat'
⚠️ 資料插入失敗（站點 500105062）: 'lat'
⚠️ 資料插入失敗（站點 500105063）: 'lat'
⚠️ 資料插入失敗（站點 500105064）: 'lat'
⚠️ 資料插入失敗（站點 500105066）: 'lat'
⚠️ 資料插入失敗（站點 500105067）: 'lat'
⚠️ 資料插入失敗（站點 500105068）: 'lat'
⚠️ 資料插入失敗（站點 500105069）: 'lat'
⚠️ 資料插入失敗（站點 500105070）: 'lat'
⚠️ 資料插入失敗（站點 500105071）: 'lat'
⚠️ 資料插入失敗（站點 500105072）: 'lat'
⚠️ 資料插入失敗（站點 500105073）: 'lat'
⚠️ 資料插入失敗（站點 500105074）: 'lat'
⚠️ 資料插入失敗（站點 500105075）: 'lat'
⚠️ 資料插入失敗（站點 500105076）: 'lat'
⚠️ 資料插入失敗（站點 500105077）: 'lat'
⚠️ 資料插入失敗（站點 500105079）: 'lat'
⚠️ 資料插入失敗（站點 500105080）: 'lat'
⚠️ 資料插入失敗（站點 500105081）: 'lat'
⚠️ 資料插入失敗（站點 500105082）: 'lat'
⚠️ 資料插入失敗（站點 500105083）: 'lat'
⚠️ 資料插入失敗（站點 500105084）: 'lat'
⚠️ 資料插入失敗（站點 500105085）: 'lat'
⚠️ 資料插入失敗（站點 500105086）: 'lat'
⚠️ 資料插入失敗（站點 500105087）: 'lat'
⚠️ 資料插入失敗（站點 500105088）: 'lat'
⚠️ 資料插入失敗（站點 500105089）: 'lat'
⚠️ 資料插入失敗（站點 500105090）: 'lat'
⚠️ 資料插入失敗（站點 500105091）: 'lat'
⚠️ 資料插入失敗（站點 500105092）: 'lat'
⚠️ 資料插入失敗（站點 500105093）: 'lat'
⚠️ 資料插入失敗（站點 500105094）: 'lat'
⚠️ 資料插入失敗（站點 500105095）: 'lat'
⚠️ 資料插入失敗（站點 500105096）: 'lat'
⚠️ 資料插入失敗（站點 500105097）: 'lat'
⚠️ 資料插入失敗（站點 500105098）: 'lat'
⚠️ 資料插入失敗（站點 500105100）: 'lat'
⚠️ 資料插入失敗（站點 500105101）: 'lat'
⚠️ 資料插入失敗（站點 500105102）: 'lat'
⚠️ 資料插入失敗（站點 500105103）: 'lat'
⚠️ 資料插入失敗（站點 500105104）: 'lat'
⚠️ 資料插入失敗（站點 500105106）: 'lat'
⚠️ 資料插入失敗（站點 500105107）: 'lat'
⚠️ 資料插入失敗（站點 500105108）: 'lat'
⚠️ 資料插入失敗（站點 500105109）: 'lat'
⚠️ 資料插入失敗（站點 500105110）: 'lat'
⚠️ 資料插入失敗（站點 500105111）: 'lat'
⚠️ 資料插入失敗（站點 500105112）: 'lat'
⚠️ 資料插入失敗（站點 500105113）: 'lat'
⚠️ 資料插入失敗（站點 500105114）: 'lat'
⚠️ 資料插入失敗（站點 500105115）: 'lat'
⚠️ 資料插入失敗（站點 500106001）: 'lat'
⚠️ 資料插入失敗（站點 500106002）: 'lat'
⚠️ 資料插入失敗（站點 500106003）: 'lat'
⚠️ 資料插入失敗（站點 500106004）: 'lat'
⚠️ 資料插入失敗（站點 500106005）: 'lat'
⚠️ 資料插入失敗（站點 500106006）: 'lat'
⚠️ 資料插入失敗（站點 500106007）: 'lat'
⚠️ 資料插入失敗（站點 500106008）: 'lat'
⚠️ 資料插入失敗（站點 500106009）: 'lat'
⚠️ 資料插入失敗（站點 500106010）: 'lat'
⚠️ 資料插入失敗（站點 500106011）: 'lat'
⚠️ 資料插入失敗（站點 500106012）: 'lat'
⚠️ 資料插入失敗（站點 500106013）: 'lat'
⚠️ 資料插入失敗（站點 500106014）: 'lat'
⚠️ 資料插入失敗（站點 500106015）: 'lat'
⚠️ 資料插入失敗（站點 500106016）: 'lat'
⚠️ 資料插入失敗（站點 500106017）: 'lat'
⚠️ 資料插入失敗（站點 500106018）: 'lat'
⚠️ 資料插入失敗（站點 500106019）: 'lat'
⚠️ 資料插入失敗（站點 500106020）: 'lat'
⚠️ 資料插入失敗（站點 500106021）: 'lat'
⚠️ 資料插入失敗（站點 500106022）: 'lat'
⚠️ 資料插入失敗（站點 500106023）: 'lat'
⚠️ 資料插入失敗（站點 500106025）: 'lat'
⚠️ 資料插入失敗（站點 500106026）: 'lat'
⚠️ 資料插入失敗（站點 500106027）: 'lat'
⚠️ 資料插入失敗（站點 500106028）: 'lat'
⚠️ 資料插入失敗（站點 500106029）: 'lat'
⚠️ 資料插入失敗（站點 500106030）: 'lat'
⚠️ 資料插入失敗（站點 500106031）: 'lat'
⚠️ 資料插入失敗（站點 500106037）: 'lat'
⚠️ 資料插入失敗（站點 500106038）: 'lat'
⚠️ 資料插入失敗（站點 500106039）: 'lat'
⚠️ 資料插入失敗（站點 500106040）: 'lat'
⚠️ 資料插入失敗（站點 500106041）: 'lat'
⚠️ 資料插入失敗（站點 500106042）: 'lat'
⚠️ 資料插入失敗（站點 500106043）: 'lat'
⚠️ 資料插入失敗（站點 500106044）: 'lat'
⚠️ 資料插入失敗（站點 500106046）: 'lat'
⚠️ 資料插入失敗（站點 500106047）: 'lat'
⚠️ 資料插入失敗（站點 500106048）: 'lat'
⚠️ 資料插入失敗（站點 500106049）: 'lat'
⚠️ 資料插入失敗（站點 500106050）: 'lat'
⚠️ 資料插入失敗（站點 500106051）: 'lat'
⚠️ 資料插入失敗（站點 500106052）: 'lat'
⚠️ 資料插入失敗（站點 500106053）: 'lat'
⚠️ 資料插入失敗（站點 500106054）: 'lat'
⚠️ 資料插入失敗（站點 500106055）: 'lat'
⚠️ 資料插入失敗（站點 500106056）: 'lat'
⚠️ 資料插入失敗（站點 500106057）: 'lat'
⚠️ 資料插入失敗（站點 500106058）: 'lat'
⚠️ 資料插入失敗（站點 500106059）: 'lat'
⚠️ 資料插入失敗（站點 500106060）: 'lat'
⚠️ 資料插入失敗（站點 500106061）: 'lat'
⚠️ 資料插入失敗（站點 500106062）: 'lat'
⚠️ 資料插入失敗（站點 500106063）: 'lat'
⚠️ 資料插入失敗（站點 500106064）: 'lat'
⚠️ 資料插入失敗（站點 500106065）: 'lat'
⚠️ 資料插入失敗（站點 500106066）: 'lat'
⚠️ 資料插入失敗（站點 500106067）: 'lat'
⚠️ 資料插入失敗（站點 500106068）: 'lat'
⚠️ 資料插入失敗（站點 500106069）: 'lat'
⚠️ 資料插入失敗（站點 500106070）: 'lat'
⚠️ 資料插入失敗（站點 500106071）: 'lat'
⚠️ 資料插入失敗（站點 500106072）: 'lat'
⚠️ 資料插入失敗（站點 500106073）: 'lat'
⚠️ 資料插入失敗（站點 500106074）: 'lat'
⚠️ 資料插入失敗（站點 500106075）: 'lat'
⚠️ 資料插入失敗（站點 500106077）: 'lat'
⚠️ 資料插入失敗（站點 500106078）: 'lat'
⚠️ 資料插入失敗（站點 500106079）: 'lat'
⚠️ 資料插入失敗（站點 500106080）: 'lat'
⚠️ 資料插入失敗（站點 500106083）: 'lat'
⚠️ 資料插入失敗（站點 500106084）: 'lat'
⚠️ 資料插入失敗（站點 500106085）: 'lat'
⚠️ 資料插入失敗（站點 500106086）: 'lat'
⚠️ 資料插入失敗（站點 500106087）: 'lat'
⚠️ 資料插入失敗（站點 500106088）: 'lat'
⚠️ 資料插入失敗（站點 500106089）: 'lat'
⚠️ 資料插入失敗（站點 500106090）: 'lat'
⚠️ 資料插入失敗（站點 500106091）: 'lat'
⚠️ 資料插入失敗（站點 500106092）: 'lat'
⚠️ 資料插入失敗（站點 500106093）: 'lat'
⚠️ 資料插入失敗（站點 500106094）: 'lat'
⚠️ 資料插入失敗（站點 500106095）: 'lat'
⚠️ 資料插入失敗（站點 500106096）: 'lat'
⚠️ 資料插入失敗（站點 500106097）: 'lat'
⚠️ 資料插入失敗（站點 500106098）: 'lat'
⚠️ 資料插入失敗（站點 500106099）: 'lat'
⚠️ 資料插入失敗（站點 500106100）: 'lat'
⚠️ 資料插入失敗（站點 500106101）: 'lat'
⚠️ 資料插入失敗（站點 500106102）: 'lat'
⚠️ 資料插入失敗（站點 500106103）: 'lat'
⚠️ 資料插入失敗（站點 500106104）: 'lat'
⚠️ 資料插入失敗（站點 500106105）: 'lat'
⚠️ 資料插入失敗（站點 500106106）: 'lat'
⚠️ 資料插入失敗（站點 500106107）: 'lat'
⚠️ 資料插入失敗（站點 500106108）: 'lat'
⚠️ 資料插入失敗（站點 500106109）: 'lat'
⚠️ 資料插入失敗（站點 500106110）: 'lat'
⚠️ 資料插入失敗（站點 500106111）: 'lat'
⚠️ 資料插入失敗（站點 500106112）: 'lat'
⚠️ 資料插入失敗（站點 500106113）: 'lat'
⚠️ 資料插入失敗（站點 500106114）: 'lat'
⚠️ 資料插入失敗（站點 500106115）: 'lat'
⚠️ 資料插入失敗（站點 500106116）: 'lat'
⚠️ 資料插入失敗（站點 500106117）: 'lat'
⚠️ 資料插入失敗（站點 500106118）: 'lat'
⚠️ 資料插入失敗（站點 500106119）: 'lat'
⚠️ 資料插入失敗（站點 500106120）: 'lat'
⚠️ 資料插入失敗（站點 500106121）: 'lat'
⚠️ 資料插入失敗（站點 500106122）: 'lat'
⚠️ 資料插入失敗（站點 500106123）: 'lat'
⚠️ 資料插入失敗（站點 500106124）: 'lat'
⚠️ 資料插入失敗（站點 500106125）: 'lat'
⚠️ 資料插入失敗（站點 500106126）: 'lat'
⚠️ 資料插入失敗（站點 500106127）: 'lat'
⚠️ 資料插入失敗（站點 500106128）: 'lat'
⚠️ 資料插入失敗（站點 500106129）: 'lat'
⚠️ 資料插入失敗（站點 500106130）: 'lat'
⚠️ 資料插入失敗（站點 500106131）: 'lat'
⚠️ 資料插入失敗（站點 500106132）: 'lat'
⚠️ 資料插入失敗（站點 500106133）: 'lat'
⚠️ 資料插入失敗（站點 500106134）: 'lat'
⚠️ 資料插入失敗（站點 500106135）: 'lat'
⚠️ 資料插入失敗（站點 500106136）: 'lat'
⚠️ 資料插入失敗（站點 500106137）: 'lat'
⚠️ 資料插入失敗（站點 500106138）: 'lat'
⚠️ 資料插入失敗（站點 500106141）: 'lat'
⚠️ 資料插入失敗（站點 500106142）: 'lat'
⚠️ 資料插入失敗（站點 500106143）: 'lat'
⚠️ 資料插入失敗（站點 500107001）: 'lat'
⚠️ 資料插入失敗（站點 500107002）: 'lat'
⚠️ 資料插入失敗（站點 500107003）: 'lat'
⚠️ 資料插入失敗（站點 500107004）: 'lat'
⚠️ 資料插入失敗（站點 500107005）: 'lat'
⚠️ 資料插入失敗（站點 500107006）: 'lat'
⚠️ 資料插入失敗（站點 500107007）: 'lat'
⚠️ 資料插入失敗（站點 500107008）: 'lat'
⚠️ 資料插入失敗（站點 500107009）: 'lat'
⚠️ 資料插入失敗（站點 500107010）: 'lat'
⚠️ 資料插入失敗（站點 500107011）: 'lat'
⚠️ 資料插入失敗（站點 500107012）: 'lat'
⚠️ 資料插入失敗（站點 500107013）: 'lat'
⚠️ 資料插入失敗（站點 500107014）: 'lat'
⚠️ 資料插入失敗（站點 500107015）: 'lat'
⚠️ 資料插入失敗（站點 500107016）: 'lat'
⚠️ 資料插入失敗（站點 500107017）: 'lat'
⚠️ 資料插入失敗（站點 500107018）: 'lat'
⚠️ 資料插入失敗（站點 500107019）: 'lat'
⚠️ 資料插入失敗（站點 500107020）: 'lat'
⚠️ 資料插入失敗（站點 500107021）: 'lat'
⚠️ 資料插入失敗（站點 500107022）: 'lat'
⚠️ 資料插入失敗（站點 500107023）: 'lat'
⚠️ 資料插入失敗（站點 500107024）: 'lat'
⚠️ 資料插入失敗（站點 500107025）: 'lat'
⚠️ 資料插入失敗（站點 500107026）: 'lat'
⚠️ 資料插入失敗（站點 500107027）: 'lat'
⚠️ 資料插入失敗（站點 500107028）: 'lat'
⚠️ 資料插入失敗（站點 500107029）: 'lat'
⚠️ 資料插入失敗（站點 500107030）: 'lat'
⚠️ 資料插入失敗（站點 500107031）: 'lat'
⚠️ 資料插入失敗（站點 500107032）: 'lat'
⚠️ 資料插入失敗（站點 500107033）: 'lat'
⚠️ 資料插入失敗（站點 500107034）: 'lat'
⚠️ 資料插入失敗（站點 500107035）: 'lat'
⚠️ 資料插入失敗（站點 500107036）: 'lat'
⚠️ 資料插入失敗（站點 500107037）: 'lat'
⚠️ 資料插入失敗（站點 500107038）: 'lat'
⚠️ 資料插入失敗（站點 500107039）: 'lat'
⚠️ 資料插入失敗（站點 500107040）: 'lat'
⚠️ 資料插入失敗（站點 500107041）: 'lat'
⚠️ 資料插入失敗（站點 500107042）: 'lat'
⚠️ 資料插入失敗（站點 500107043）: 'lat'
⚠️ 資料插入失敗（站點 500107044）: 'lat'
⚠️ 資料插入失敗（站點 500107045）: 'lat'
⚠️ 資料插入失敗（站點 500107046）: 'lat'
⚠️ 資料插入失敗（站點 500107047）: 'lat'
⚠️ 資料插入失敗（站點 500107048）: 'lat'
⚠️ 資料插入失敗（站點 500107049）: 'lat'
⚠️ 資料插入失敗（站點 500107050）: 'lat'
⚠️ 資料插入失敗（站點 500107051）: 'lat'
⚠️ 資料插入失敗（站點 500107052）: 'lat'
⚠️ 資料插入失敗（站點 500107053）: 'lat'
⚠️ 資料插入失敗（站點 500107054）: 'lat'
⚠️ 資料插入失敗（站點 500107055）: 'lat'
⚠️ 資料插入失敗（站點 500107056）: 'lat'
⚠️ 資料插入失敗（站點 500107058）: 'lat'
⚠️ 資料插入失敗（站點 500107059）: 'lat'
⚠️ 資料插入失敗（站點 500107060）: 'lat'
⚠️ 資料插入失敗（站點 500107061）: 'lat'
⚠️ 資料插入失敗（站點 500107062）: 'lat'
⚠️ 資料插入失敗（站點 500107063）: 'lat'
⚠️ 資料插入失敗（站點 500107064）: 'lat'
⚠️ 資料插入失敗（站點 500107065）: 'lat'
⚠️ 資料插入失敗（站點 500107066）: 'lat'
⚠️ 資料插入失敗（站點 500107067）: 'lat'
⚠️ 資料插入失敗（站點 500107068）: 'lat'
⚠️ 資料插入失敗（站點 500107069）: 'lat'
⚠️ 資料插入失敗（站點 500107070）: 'lat'
⚠️ 資料插入失敗（站點 500107071）: 'lat'
⚠️ 資料插入失敗（站點 500107072）: 'lat'
⚠️ 資料插入失敗（站點 500107075）: 'lat'
⚠️ 資料插入失敗（站點 500107076）: 'lat'
⚠️ 資料插入失敗（站點 500107077）: 'lat'
⚠️ 資料插入失敗（站點 500107078）: 'lat'
⚠️ 資料插入失敗（站點 500107079）: 'lat'
⚠️ 資料插入失敗（站點 500107080）: 'lat'
⚠️ 資料插入失敗（站點 500107081）: 'lat'
⚠️ 資料插入失敗（站點 500107082）: 'lat'
⚠️ 資料插入失敗（站點 500107083）: 'lat'
⚠️ 資料插入失敗（站點 500107084）: 'lat'
⚠️ 資料插入失敗（站點 500107085）: 'lat'
⚠️ 資料插入失敗（站點 500107086）: 'lat'
⚠️ 資料插入失敗（站點 500107087）: 'lat'
⚠️ 資料插入失敗（站點 500107088）: 'lat'
⚠️ 資料插入失敗（站點 500107089）: 'lat'
⚠️ 資料插入失敗（站點 500107090）: 'lat'
⚠️ 資料插入失敗（站點 500107091）: 'lat'
⚠️ 資料插入失敗（站點 500107092）: 'lat'
⚠️ 資料插入失敗（站點 500107093）: 'lat'
⚠️ 資料插入失敗（站點 500107095）: 'lat'
⚠️ 資料插入失敗（站點 500107096）: 'lat'
⚠️ 資料插入失敗（站點 500107097）: 'lat'
⚠️ 資料插入失敗（站點 500107098）: 'lat'
⚠️ 資料插入失敗（站點 500107099）: 'lat'
⚠️ 資料插入失敗（站點 500107100）: 'lat'
⚠️ 資料插入失敗（站點 500107101）: 'lat'
⚠️ 資料插入失敗（站點 500107102）: 'lat'
⚠️ 資料插入失敗（站點 500107103）: 'lat'
⚠️ 資料插入失敗（站點 500107104）: 'lat'
⚠️ 資料插入失敗（站點 500107105）: 'lat'
⚠️ 資料插入失敗（站點 500107106）: 'lat'
⚠️ 資料插入失敗（站點 500107107）: 'lat'
⚠️ 資料插入失敗（站點 500107108）: 'lat'
⚠️ 資料插入失敗（站點 500107109）: 'lat'
⚠️ 資料插入失敗（站點 500107110）: 'lat'
⚠️ 資料插入失敗（站點 500107111）: 'lat'
⚠️ 資料插入失敗（站點 500107112）: 'lat'
⚠️ 資料插入失敗（站點 500107113）: 'lat'
⚠️ 資料插入失敗（站點 500107114）: 'lat'
⚠️ 資料插入失敗（站點 500107115）: 'lat'
⚠️ 資料插入失敗（站點 500107116）: 'lat'
⚠️ 資料插入失敗（站點 500107117）: 'lat'
⚠️ 資料插入失敗（站點 500107118）: 'lat'
⚠️ 資料插入失敗（站點 500107119）: 'lat'
⚠️ 資料插入失敗（站點 500107120）: 'lat'
⚠️ 資料插入失敗（站點 500107121）: 'lat'
⚠️ 資料插入失敗（站點 500107122）: 'lat'
⚠️ 資料插入失敗（站點 500107123）: 'lat'
⚠️ 資料插入失敗（站點 500107124）: 'lat'
⚠️ 資料插入失敗（站點 500107125）: 'lat'
⚠️ 資料插入失敗（站點 500107126）: 'lat'
⚠️ 資料插入失敗（站點 500107127）: 'lat'
⚠️ 資料插入失敗（站點 500107128）: 'lat'
⚠️ 資料插入失敗（站點 500107129）: 'lat'
⚠️ 資料插入失敗（站點 500107130）: 'lat'
⚠️ 資料插入失敗（站點 500107131）: 'lat'
⚠️ 資料插入失敗（站點 500107132）: 'lat'
⚠️ 資料插入失敗（站點 500107133）: 'lat'
⚠️ 資料插入失敗（站點 500107134）: 'lat'
⚠️ 資料插入失敗（站點 500107135）: 'lat'
⚠️ 資料插入失敗（站點 500107136）: 'lat'
⚠️ 資料插入失敗（站點 500107137）: 'lat'
⚠️ 資料插入失敗（站點 500107138）: 'lat'
⚠️ 資料插入失敗（站點 500107139）: 'lat'
⚠️ 資料插入失敗（站點 500107140）: 'lat'
⚠️ 資料插入失敗（站點 500107141）: 'lat'
⚠️ 資料插入失敗（站點 500107142）: 'lat'
⚠️ 資料插入失敗（站點 500107143）: 'lat'
⚠️ 資料插入失敗（站點 500107144）: 'lat'
⚠️ 資料插入失敗（站點 500107145）: 'lat'
⚠️ 資料插入失敗（站點 500107146）: 'lat'
⚠️ 資料插入失敗（站點 500107147）: 'lat'
⚠️ 資料插入失敗（站點 500107149）: 'lat'
⚠️ 資料插入失敗（站點 500107150）: 'lat'
⚠️ 資料插入失敗（站點 500107151）: 'lat'
⚠️ 資料插入失敗（站點 500107152）: 'lat'
⚠️ 資料插入失敗（站點 500107153）: 'lat'
⚠️ 資料插入失敗（站點 500107154）: 'lat'
⚠️ 資料插入失敗（站點 500107155）: 'lat'
⚠️ 資料插入失敗（站點 500107156）: 'lat'
⚠️ 資料插入失敗（站點 500107157）: 'lat'
⚠️ 資料插入失敗（站點 500107158）: 'lat'
⚠️ 資料插入失敗（站點 500107159）: 'lat'
⚠️ 資料插入失敗（站點 500107160）: 'lat'
⚠️ 資料插入失敗（站點 500107161）: 'lat'
⚠️ 資料插入失敗（站點 500107162）: 'lat'
⚠️ 資料插入失敗（站點 500107163）: 'lat'
⚠️ 資料插入失敗（站點 500107164）: 'lat'
⚠️ 資料插入失敗（站點 500107165）: 'lat'
⚠️ 資料插入失敗（站點 500107166）: 'lat'
⚠️ 資料插入失敗（站點 500107167）: 'lat'
⚠️ 資料插入失敗（站點 500107168）: 'lat'
⚠️ 資料插入失敗（站點 500107169）: 'lat'
⚠️ 資料插入失敗（站點 500107170）: 'lat'
⚠️ 資料插入失敗（站點 500107171）: 'lat'
⚠️ 資料插入失敗（站點 500107172）: 'lat'
⚠️ 資料插入失敗（站點 500107173）: 'lat'
⚠️ 資料插入失敗（站點 500107174）: 'lat'
⚠️ 資料插入失敗（站點 500107175）: 'lat'
⚠️ 資料插入失敗（站點 500107176）: 'lat'
⚠️ 資料插入失敗（站點 500107177）: 'lat'
⚠️ 資料插入失敗（站點 500107178）: 'lat'
⚠️ 資料插入失敗（站點 500107179）: 'lat'
⚠️ 資料插入失敗（站點 500107180）: 'lat'
⚠️ 資料插入失敗（站點 500107181）: 'lat'
⚠️ 資料插入失敗（站點 500107182）: 'lat'
⚠️ 資料插入失敗（站點 500107183）: 'lat'
⚠️ 資料插入失敗（站點 500107184）: 'lat'
⚠️ 資料插入失敗（站點 500107185）: 'lat'
⚠️ 資料插入失敗（站點 500107186）: 'lat'
⚠️ 資料插入失敗（站點 500107187）: 'lat'
⚠️ 資料插入失敗（站點 500107188）: 'lat'
⚠️ 資料插入失敗（站點 500107189）: 'lat'
⚠️ 資料插入失敗（站點 500108001）: 'lat'
⚠️ 資料插入失敗（站點 500108002）: 'lat'
⚠️ 資料插入失敗（站點 500108003）: 'lat'
⚠️ 資料插入失敗（站點 500108004）: 'lat'
⚠️ 資料插入失敗（站點 500108005）: 'lat'
⚠️ 資料插入失敗（站點 500108006）: 'lat'
⚠️ 資料插入失敗（站點 500108007）: 'lat'
⚠️ 資料插入失敗（站點 500108008）: 'lat'
⚠️ 資料插入失敗（站點 500108009）: 'lat'
⚠️ 資料插入失敗（站點 500108010）: 'lat'
⚠️ 資料插入失敗（站點 500108011）: 'lat'
⚠️ 資料插入失敗（站點 500108012）: 'lat'
⚠️ 資料插入失敗（站點 500108013）: 'lat'
⚠️ 資料插入失敗（站點 500108014）: 'lat'
⚠️ 資料插入失敗（站點 500108015）: 'lat'
⚠️ 資料插入失敗（站點 500108016）: 'lat'
⚠️ 資料插入失敗（站點 500108018）: 'lat'
⚠️ 資料插入失敗（站點 500108019）: 'lat'
⚠️ 資料插入失敗（站點 500108020）: 'lat'
⚠️ 資料插入失敗（站點 500108021）: 'lat'
⚠️ 資料插入失敗（站點 500108022）: 'lat'
⚠️ 資料插入失敗（站點 500108023）: 'lat'
⚠️ 資料插入失敗（站點 500108024）: 'lat'
⚠️ 資料插入失敗（站點 500108025）: 'lat'
⚠️ 資料插入失敗（站點 500108026）: 'lat'
⚠️ 資料插入失敗（站點 500108027）: 'lat'
⚠️ 資料插入失敗（站點 500108028）: 'lat'
⚠️ 資料插入失敗（站點 500108029）: 'lat'
⚠️ 資料插入失敗（站點 500108030）: 'lat'
⚠️ 資料插入失敗（站點 500108031）: 'lat'
⚠️ 資料插入失敗（站點 500108032）: 'lat'
⚠️ 資料插入失敗（站點 500108033）: 'lat'
⚠️ 資料插入失敗（站點 500108034）: 'lat'
⚠️ 資料插入失敗（站點 500108035）: 'lat'
⚠️ 資料插入失敗（站點 500108036）: 'lat'
⚠️ 資料插入失敗（站點 500108037）: 'lat'
⚠️ 資料插入失敗（站點 500108038）: 'lat'
⚠️ 資料插入失敗（站點 500108039）: 'lat'
⚠️ 資料插入失敗（站點 500108040）: 'lat'
⚠️ 資料插入失敗（站點 500108041）: 'lat'
⚠️ 資料插入失敗（站點 500108043）: 'lat'
⚠️ 資料插入失敗（站點 500108044）: 'lat'
⚠️ 資料插入失敗（站點 500108045）: 'lat'
⚠️ 資料插入失敗（站點 500108046）: 'lat'
⚠️ 資料插入失敗（站點 500108047）: 'lat'
⚠️ 資料插入失敗（站點 500108048）: 'lat'
⚠️ 資料插入失敗（站點 500108049）: 'lat'
⚠️ 資料插入失敗（站點 500108050）: 'lat'
⚠️ 資料插入失敗（站點 500108051）: 'lat'
⚠️ 資料插入失敗（站點 500108052）: 'lat'
⚠️ 資料插入失敗（站點 500108054）: 'lat'
⚠️ 資料插入失敗（站點 500108055）: 'lat'
⚠️ 資料插入失敗（站點 500108056）: 'lat'
⚠️ 資料插入失敗（站點 500108057）: 'lat'
⚠️ 資料插入失敗（站點 500108058）: 'lat'
⚠️ 資料插入失敗（站點 500108059）: 'lat'
⚠️ 資料插入失敗（站點 500108060）: 'lat'
⚠️ 資料插入失敗（站點 500108061）: 'lat'
⚠️ 資料插入失敗（站點 500108062）: 'lat'
⚠️ 資料插入失敗（站點 500108063）: 'lat'
⚠️ 資料插入失敗（站點 500108064）: 'lat'
⚠️ 資料插入失敗（站點 500108065）: 'lat'
⚠️ 資料插入失敗（站點 500108066）: 'lat'
⚠️ 資料插入失敗（站點 500108067）: 'lat'
⚠️ 資料插入失敗（站點 500108068）: 'lat'
⚠️ 資料插入失敗（站點 500108069）: 'lat'
⚠️ 資料插入失敗（站點 500108070）: 'lat'
⚠️ 資料插入失敗（站點 500108071）: 'lat'
⚠️ 資料插入失敗（站點 500108072）: 'lat'
⚠️ 資料插入失敗（站點 500108073）: 'lat'
⚠️ 資料插入失敗（站點 500108074）: 'lat'
⚠️ 資料插入失敗（站點 500108075）: 'lat'
⚠️ 資料插入失敗（站點 500108076）: 'lat'
⚠️ 資料插入失敗（站點 500108077）: 'lat'
⚠️ 資料插入失敗（站點 500108078）: 'lat'
⚠️ 資料插入失敗（站點 500108079）: 'lat'
⚠️ 資料插入失敗（站點 500108081）: 'lat'
⚠️ 資料插入失敗（站點 500108082）: 'lat'
⚠️ 資料插入失敗（站點 500108083）: 'lat'
⚠️ 資料插入失敗（站點 500108084）: 'lat'
⚠️ 資料插入失敗（站點 500108085）: 'lat'
⚠️ 資料插入失敗（站點 500108086）: 'lat'
⚠️ 資料插入失敗（站點 500108087）: 'lat'
⚠️ 資料插入失敗（站點 500108088）: 'lat'
⚠️ 資料插入失敗（站點 500108089）: 'lat'
⚠️ 資料插入失敗（站點 500108090）: 'lat'
⚠️ 資料插入失敗（站點 500108091）: 'lat'
⚠️ 資料插入失敗（站點 500108092）: 'lat'
⚠️ 資料插入失敗（站點 500108093）: 'lat'
⚠️ 資料插入失敗（站點 500108094）: 'lat'
⚠️ 資料插入失敗（站點 500108095）: 'lat'
⚠️ 資料插入失敗（站點 500108096）: 'lat'
⚠️ 資料插入失敗（站點 500108097）: 'lat'
⚠️ 資料插入失敗（站點 500108098）: 'lat'
⚠️ 資料插入失敗（站點 500108099）: 'lat'
⚠️ 資料插入失敗（站點 500108100）: 'lat'
⚠️ 資料插入失敗（站點 500108102）: 'lat'
⚠️ 資料插入失敗（站點 500108103）: 'lat'
⚠️ 資料插入失敗（站點 500108104）: 'lat'
⚠️ 資料插入失敗（站點 500108105）: 'lat'
⚠️ 資料插入失敗（站點 500108106）: 'lat'
⚠️ 資料插入失敗（站點 500108107）: 'lat'
⚠️ 資料插入失敗（站點 500108108）: 'lat'
⚠️ 資料插入失敗（站點 500108109）: 'lat'
⚠️ 資料插入失敗（站點 500108110）: 'lat'
⚠️ 資料插入失敗（站點 500108111）: 'lat'
⚠️ 資料插入失敗（站點 500108112）: 'lat'
⚠️ 資料插入失敗（站點 500108115）: 'lat'
⚠️ 資料插入失敗（站點 500108116）: 'lat'
⚠️ 資料插入失敗（站點 500108117）: 'lat'
⚠️ 資料插入失敗（站點 500108118）: 'lat'
⚠️ 資料插入失敗（站點 500108119）: 'lat'
⚠️ 資料插入失敗（站點 500108120）: 'lat'
⚠️ 資料插入失敗（站點 500108121）: 'lat'
⚠️ 資料插入失敗（站點 500108122）: 'lat'
⚠️ 資料插入失敗（站點 500108123）: 'lat'
⚠️ 資料插入失敗（站點 500108124）: 'lat'
⚠️ 資料插入失敗（站點 500108126）: 'lat'
⚠️ 資料插入失敗（站點 500108127）: 'lat'
⚠️ 資料插入失敗（站點 500108128）: 'lat'
⚠️ 資料插入失敗（站點 500108129）: 'lat'
⚠️ 資料插入失敗（站點 500108131）: 'lat'
⚠️ 資料插入失敗（站點 500108132）: 'lat'
⚠️ 資料插入失敗（站點 500108133）: 'lat'
⚠️ 資料插入失敗（站點 500108134）: 'lat'
⚠️ 資料插入失敗（站點 500108135）: 'lat'
⚠️ 資料插入失敗（站點 500108136）: 'lat'
⚠️ 資料插入失敗（站點 500108137）: 'lat'
⚠️ 資料插入失敗（站點 500108138）: 'lat'
⚠️ 資料插入失敗（站點 500108139）: 'lat'
⚠️ 資料插入失敗（站點 500108140）: 'lat'
⚠️ 資料插入失敗（站點 500108141）: 'lat'
⚠️ 資料插入失敗（站點 500108142）: 'lat'
⚠️ 資料插入失敗（站點 500108143）: 'lat'
⚠️ 資料插入失敗（站點 500108144）: 'lat'
⚠️ 資料插入失敗（站點 500108145）: 'lat'
⚠️ 資料插入失敗（站點 500108146）: 'lat'
⚠️ 資料插入失敗（站點 500108147）: 'lat'
⚠️ 資料插入失敗（站點 500108148）: 'lat'
⚠️ 資料插入失敗（站點 500108150）: 'lat'
⚠️ 資料插入失敗（站點 500108151）: 'lat'
⚠️ 資料插入失敗（站點 500108152）: 'lat'
⚠️ 資料插入失敗（站點 500108153）: 'lat'
⚠️ 資料插入失敗（站點 500108154）: 'lat'
⚠️ 資料插入失敗（站點 500108156）: 'lat'
⚠️ 資料插入失敗（站點 500108157）: 'lat'
⚠️ 資料插入失敗（站點 500108158）: 'lat'
⚠️ 資料插入失敗（站點 500108159）: 'lat'
⚠️ 資料插入失敗（站點 500108160）: 'lat'
⚠️ 資料插入失敗（站點 500108161）: 'lat'
⚠️ 資料插入失敗（站點 500108162）: 'lat'
⚠️ 資料插入失敗（站點 500108164）: 'lat'
⚠️ 資料插入失敗（站點 500108165）: 'lat'
⚠️ 資料插入失敗（站點 500108166）: 'lat'
⚠️ 資料插入失敗（站點 500108167）: 'lat'
⚠️ 資料插入失敗（站點 500108168）: 'lat'
⚠️ 資料插入失敗（站點 500108169）: 'lat'
⚠️ 資料插入失敗（站點 500108170）: 'lat'
⚠️ 資料插入失敗（站點 500108171）: 'lat'
⚠️ 資料插入失敗（站點 500108172）: 'lat'
⚠️ 資料插入失敗（站點 500108173）: 'lat'
⚠️ 資料插入失敗（站點 500108174）: 'lat'
⚠️ 資料插入失敗（站點 500108175）: 'lat'
⚠️ 資料插入失敗（站點 500108176）: 'lat'
⚠️ 資料插入失敗（站點 500108177）: 'lat'
⚠️ 資料插入失敗（站點 500108178）: 'lat'
⚠️ 資料插入失敗（站點 500108179）: 'lat'
⚠️ 資料插入失敗（站點 500108181）: 'lat'
⚠️ 資料插入失敗（站點 500108182）: 'lat'
⚠️ 資料插入失敗（站點 500108183）: 'lat'
⚠️ 資料插入失敗（站點 500108184）: 'lat'
⚠️ 資料插入失敗（站點 500108185）: 'lat'
⚠️ 資料插入失敗（站點 500108186）: 'lat'
⚠️ 資料插入失敗（站點 500108187）: 'lat'
⚠️ 資料插入失敗（站點 500108188）: 'lat'
⚠️ 資料插入失敗（站點 500108189）: 'lat'
⚠️ 資料插入失敗（站點 500108190）: 'lat'
⚠️ 資料插入失敗（站點 500108191）: 'lat'
⚠️ 資料插入失敗（站點 500108192）: 'lat'
⚠️ 資料插入失敗（站點 500108193）: 'lat'
⚠️ 資料插入失敗（站點 500108194）: 'lat'
⚠️ 資料插入失敗（站點 500108195）: 'lat'
⚠️ 資料插入失敗（站點 500108196）: 'lat'
⚠️ 資料插入失敗（站點 500108197）: 'lat'
⚠️ 資料插入失敗（站點 500108199）: 'lat'
⚠️ 資料插入失敗（站點 500108200）: 'lat'
⚠️ 資料插入失敗（站點 500108201）: 'lat'
⚠️ 資料插入失敗（站點 500108202）: 'lat'
⚠️ 資料插入失敗（站點 500108203）: 'lat'
⚠️ 資料插入失敗（站點 500108204）: 'lat'
⚠️ 資料插入失敗（站點 500108205）: 'lat'
⚠️ 資料插入失敗（站點 500108206）: 'lat'
⚠️ 資料插入失敗（站點 500108207）: 'lat'
⚠️ 資料插入失敗（站點 500108208）: 'lat'
⚠️ 資料插入失敗（站點 500108209）: 'lat'
⚠️ 資料插入失敗（站點 500109001）: 'lat'
⚠️ 資料插入失敗（站點 500109002）: 'lat'
⚠️ 資料插入失敗（站點 500109003）: 'lat'
⚠️ 資料插入失敗（站點 500109004）: 'lat'
⚠️ 資料插入失敗（站點 500109005）: 'lat'
⚠️ 資料插入失敗（站點 500109006）: 'lat'
⚠️ 資料插入失敗（站點 500109007）: 'lat'
⚠️ 資料插入失敗（站點 500109008）: 'lat'
⚠️ 資料插入失敗（站點 500109009）: 'lat'
⚠️ 資料插入失敗（站點 500109010）: 'lat'
⚠️ 資料插入失敗（站點 500109011）: 'lat'
⚠️ 資料插入失敗（站點 500109012）: 'lat'
⚠️ 資料插入失敗（站點 500109013）: 'lat'
⚠️ 資料插入失敗（站點 500109014）: 'lat'
⚠️ 資料插入失敗（站點 500109015）: 'lat'
⚠️ 資料插入失敗（站點 500109016）: 'lat'
⚠️ 資料插入失敗（站點 500109017）: 'lat'
⚠️ 資料插入失敗（站點 500109018）: 'lat'
⚠️ 資料插入失敗（站點 500109019）: 'lat'
⚠️ 資料插入失敗（站點 500109020）: 'lat'
⚠️ 資料插入失敗（站點 500109022）: 'lat'
⚠️ 資料插入失敗（站點 500109023）: 'lat'
⚠️ 資料插入失敗（站點 500109024）: 'lat'
⚠️ 資料插入失敗（站點 500109025）: 'lat'
⚠️ 資料插入失敗（站點 500109026）: 'lat'
⚠️ 資料插入失敗（站點 500109027）: 'lat'
⚠️ 資料插入失敗（站點 500109028）: 'lat'
⚠️ 資料插入失敗（站點 500109029）: 'lat'
⚠️ 資料插入失敗（站點 500109030）: 'lat'
⚠️ 資料插入失敗（站點 500109031）: 'lat'
⚠️ 資料插入失敗（站點 500109032）: 'lat'
⚠️ 資料插入失敗（站點 500109033）: 'lat'
⚠️ 資料插入失敗（站點 500109034）: 'lat'
⚠️ 資料插入失敗（站點 500109035）: 'lat'
⚠️ 資料插入失敗（站點 500109036）: 'lat'
⚠️ 資料插入失敗（站點 500109037）: 'lat'
⚠️ 資料插入失敗（站點 500109039）: 'lat'
⚠️ 資料插入失敗（站點 500109040）: 'lat'
⚠️ 資料插入失敗（站點 500109041）: 'lat'
⚠️ 資料插入失敗（站點 500109042）: 'lat'
⚠️ 資料插入失敗（站點 500109043）: 'lat'
⚠️ 資料插入失敗（站點 500109044）: 'lat'
⚠️ 資料插入失敗（站點 500109045）: 'lat'
⚠️ 資料插入失敗（站點 500109046）: 'lat'
⚠️ 資料插入失敗（站點 500109047）: 'lat'
⚠️ 資料插入失敗（站點 500109048）: 'lat'
⚠️ 資料插入失敗（站點 500109049）: 'lat'
⚠️ 資料插入失敗（站點 500109050）: 'lat'
⚠️ 資料插入失敗（站點 500109051）: 'lat'
⚠️ 資料插入失敗（站點 500109052）: 'lat'
⚠️ 資料插入失敗（站點 500109053）: 'lat'
⚠️ 資料插入失敗（站點 500109054）: 'lat'
⚠️ 資料插入失敗（站點 500109055）: 'lat'
⚠️ 資料插入失敗（站點 500109056）: 'lat'
⚠️ 資料插入失敗（站點 500109057）: 'lat'
⚠️ 資料插入失敗（站點 500109058）: 'lat'
⚠️ 資料插入失敗（站點 500109059）: 'lat'
⚠️ 資料插入失敗（站點 500109060）: 'lat'
⚠️ 資料插入失敗（站點 500109061）: 'lat'
⚠️ 資料插入失敗（站點 500109062）: 'lat'
⚠️ 資料插入失敗（站點 500109063）: 'lat'
⚠️ 資料插入失敗（站點 500109064）: 'lat'
⚠️ 資料插入失敗（站點 500109065）: 'lat'
⚠️ 資料插入失敗（站點 500109066）: 'lat'
⚠️ 資料插入失敗（站點 500109067）: 'lat'
⚠️ 資料插入失敗（站點 500109068）: 'lat'
⚠️ 資料插入失敗（站點 500109070）: 'lat'
⚠️ 資料插入失敗（站點 500109071）: 'lat'
⚠️ 資料插入失敗（站點 500109072）: 'lat'
⚠️ 資料插入失敗（站點 500109073）: 'lat'
⚠️ 資料插入失敗（站點 500109074）: 'lat'
⚠️ 資料插入失敗（站點 500109075）: 'lat'
⚠️ 資料插入失敗（站點 500109076）: 'lat'
⚠️ 資料插入失敗（站點 500109077）: 'lat'
⚠️ 資料插入失敗（站點 500109078）: 'lat'
⚠️ 資料插入失敗（站點 500109079）: 'lat'
⚠️ 資料插入失敗（站點 500109080）: 'lat'
⚠️ 資料插入失敗（站點 500109081）: 'lat'
⚠️ 資料插入失敗（站點 500109082）: 'lat'
⚠️ 資料插入失敗（站點 500109084）: 'lat'
⚠️ 資料插入失敗（站點 500109085）: 'lat'
⚠️ 資料插入失敗（站點 500109086）: 'lat'
⚠️ 資料插入失敗（站點 500109087）: 'lat'
⚠️ 資料插入失敗（站點 500109088）: 'lat'
⚠️ 資料插入失敗（站點 500109089）: 'lat'
⚠️ 資料插入失敗（站點 500109091）: 'lat'
⚠️ 資料插入失敗（站點 500109092）: 'lat'
⚠️ 資料插入失敗（站點 500109093）: 'lat'
⚠️ 資料插入失敗（站點 500109094）: 'lat'
⚠️ 資料插入失敗（站點 500109095）: 'lat'
⚠️ 資料插入失敗（站點 500109096）: 'lat'
⚠️ 資料插入失敗（站點 500109097）: 'lat'
⚠️ 資料插入失敗（站點 500109098）: 'lat'
⚠️ 資料插入失敗（站點 500109099）: 'lat'
⚠️ 資料插入失敗（站點 500109100）: 'lat'
⚠️ 資料插入失敗（站點 500109101）: 'lat'
⚠️ 資料插入失敗（站點 500109102）: 'lat'
⚠️ 資料插入失敗（站點 500109103）: 'lat'
⚠️ 資料插入失敗（站點 500109104）: 'lat'
⚠️ 資料插入失敗（站點 500109105）: 'lat'
⚠️ 資料插入失敗（站點 500109106）: 'lat'
⚠️ 資料插入失敗（站點 500109107）: 'lat'
⚠️ 資料插入失敗（站點 500109108）: 'lat'
⚠️ 資料插入失敗（站點 500109109）: 'lat'
⚠️ 資料插入失敗（站點 500109111）: 'lat'
⚠️ 資料插入失敗（站點 500109112）: 'lat'
⚠️ 資料插入失敗（站點 500109113）: 'lat'
⚠️ 資料插入失敗（站點 500110002）: 'lat'
⚠️ 資料插入失敗（站點 500110003）: 'lat'
⚠️ 資料插入失敗（站點 500110004）: 'lat'
⚠️ 資料插入失敗（站點 500110005）: 'lat'
⚠️ 資料插入失敗（站點 500110006）: 'lat'
⚠️ 資料插入失敗（站點 500110007）: 'lat'
⚠️ 資料插入失敗（站點 500110008）: 'lat'
⚠️ 資料插入失敗（站點 500110009）: 'lat'
⚠️ 資料插入失敗（站點 500110010）: 'lat'
⚠️ 資料插入失敗（站點 500110011）: 'lat'
⚠️ 資料插入失敗（站點 500110012）: 'lat'
⚠️ 資料插入失敗（站點 500110013）: 'lat'
⚠️ 資料插入失敗（站點 500110014）: 'lat'
⚠️ 資料插入失敗（站點 500110015）: 'lat'
⚠️ 資料插入失敗（站點 500110016）: 'lat'
⚠️ 資料插入失敗（站點 500110017）: 'lat'
⚠️ 資料插入失敗（站點 500110018）: 'lat'
⚠️ 資料插入失敗（站點 500110019）: 'lat'
⚠️ 資料插入失敗（站點 500110020）: 'lat'
⚠️ 資料插入失敗（站點 500110021）: 'lat'
⚠️ 資料插入失敗（站點 500110022）: 'lat'
⚠️ 資料插入失敗（站點 500110023）: 'lat'
⚠️ 資料插入失敗（站點 500110024）: 'lat'
⚠️ 資料插入失敗（站點 500110025）: 'lat'
⚠️ 資料插入失敗（站點 500110026）: 'lat'
⚠️ 資料插入失敗（站點 500110027）: 'lat'
⚠️ 資料插入失敗（站點 500110028）: 'lat'
⚠️ 資料插入失敗（站點 500110029）: 'lat'
⚠️ 資料插入失敗（站點 500110030）: 'lat'
⚠️ 資料插入失敗（站點 500110031）: 'lat'
⚠️ 資料插入失敗（站點 500110032）: 'lat'
⚠️ 資料插入失敗（站點 500110033）: 'lat'
⚠️ 資料插入失敗（站點 500110034）: 'lat'
⚠️ 資料插入失敗（站點 500110035）: 'lat'
⚠️ 資料插入失敗（站點 500110036）: 'lat'
⚠️ 資料插入失敗（站點 500110037）: 'lat'
⚠️ 資料插入失敗（站點 500110038）: 'lat'
⚠️ 資料插入失敗（站點 500110039）: 'lat'
⚠️ 資料插入失敗（站點 500110040）: 'lat'
⚠️ 資料插入失敗（站點 500110041）: 'lat'
⚠️ 資料插入失敗（站點 500110042）: 'lat'
⚠️ 資料插入失敗（站點 500110043）: 'lat'
⚠️ 資料插入失敗（站點 500110044）: 'lat'
⚠️ 資料插入失敗（站點 500110045）: 'lat'
⚠️ 資料插入失敗（站點 500110046）: 'lat'
⚠️ 資料插入失敗（站點 500110047）: 'lat'
⚠️ 資料插入失敗（站點 500110048）: 'lat'
⚠️ 資料插入失敗（站點 500110049）: 'lat'
⚠️ 資料插入失敗（站點 500110050）: 'lat'
⚠️ 資料插入失敗（站點 500110051）: 'lat'
⚠️ 資料插入失敗（站點 500110052）: 'lat'
⚠️ 資料插入失敗（站點 500110053）: 'lat'
⚠️ 資料插入失敗（站點 500110054）: 'lat'
⚠️ 資料插入失敗（站點 500110055）: 'lat'
⚠️ 資料插入失敗（站點 500110056）: 'lat'
⚠️ 資料插入失敗（站點 500110057）: 'lat'
⚠️ 資料插入失敗（站點 500110058）: 'lat'
⚠️ 資料插入失敗（站點 500110059）: 'lat'
⚠️ 資料插入失敗（站點 500110060）: 'lat'
⚠️ 資料插入失敗（站點 500110061）: 'lat'
⚠️ 資料插入失敗（站點 500110062）: 'lat'
⚠️ 資料插入失敗（站點 500110063）: 'lat'
⚠️ 資料插入失敗（站點 500110064）: 'lat'
⚠️ 資料插入失敗（站點 500110065）: 'lat'
⚠️ 資料插入失敗（站點 500110066）: 'lat'
⚠️ 資料插入失敗（站點 500110067）: 'lat'
⚠️ 資料插入失敗（站點 500110068）: 'lat'
⚠️ 資料插入失敗（站點 500110069）: 'lat'
⚠️ 資料插入失敗（站點 500110070）: 'lat'
⚠️ 資料插入失敗（站點 500110071）: 'lat'
⚠️ 資料插入失敗（站點 500110072）: 'lat'
⚠️ 資料插入失敗（站點 500110073）: 'lat'
⚠️ 資料插入失敗（站點 500110074）: 'lat'
⚠️ 資料插入失敗（站點 500110076）: 'lat'
⚠️ 資料插入失敗（站點 500110077）: 'lat'
⚠️ 資料插入失敗（站點 500110078）: 'lat'
⚠️ 資料插入失敗（站點 500110079）: 'lat'
⚠️ 資料插入失敗（站點 500110080）: 'lat'
⚠️ 資料插入失敗（站點 500110081）: 'lat'
⚠️ 資料插入失敗（站點 500110082）: 'lat'
⚠️ 資料插入失敗（站點 500110083）: 'lat'
⚠️ 資料插入失敗（站點 500110084）: 'lat'
⚠️ 資料插入失敗（站點 500110085）: 'lat'
⚠️ 資料插入失敗（站點 500110086）: 'lat'
⚠️ 資料插入失敗（站點 500110087）: 'lat'
⚠️ 資料插入失敗（站點 500110088）: 'lat'
⚠️ 資料插入失敗（站點 500110089）: 'lat'
⚠️ 資料插入失敗（站點 500110090）: 'lat'
⚠️ 資料插入失敗（站點 500110091）: 'lat'
⚠️ 資料插入失敗（站點 500110092）: 'lat'
⚠️ 資料插入失敗（站點 500110093）: 'lat'
⚠️ 資料插入失敗（站點 500110095）: 'lat'
⚠️ 資料插入失敗（站點 500110096）: 'lat'
⚠️ 資料插入失敗（站點 500110097）: 'lat'
⚠️ 資料插入失敗（站點 500110098）: 'lat'
⚠️ 資料插入失敗（站點 500110099）: 'lat'
⚠️ 資料插入失敗（站點 500110100）: 'lat'
⚠️ 資料插入失敗（站點 500110101）: 'lat'
⚠️ 資料插入失敗（站點 500111001）: 'lat'
⚠️ 資料插入失敗（站點 500111002）: 'lat'
⚠️ 資料插入失敗（站點 500111003）: 'lat'
⚠️ 資料插入失敗（站點 500111004）: 'lat'
⚠️ 資料插入失敗（站點 500111005）: 'lat'
⚠️ 資料插入失敗（站點 500111006）: 'lat'
⚠️ 資料插入失敗（站點 500111007）: 'lat'
⚠️ 資料插入失敗（站點 500111008）: 'lat'
⚠️ 資料插入失敗（站點 500111009）: 'lat'
⚠️ 資料插入失敗（站點 500111010）: 'lat'
⚠️ 資料插入失敗（站點 500111011）: 'lat'
⚠️ 資料插入失敗（站點 500111012）: 'lat'
⚠️ 資料插入失敗（站點 500111013）: 'lat'
⚠️ 資料插入失敗（站點 500111014）: 'lat'
⚠️ 資料插入失敗（站點 500111015）: 'lat'
⚠️ 資料插入失敗（站點 500111016）: 'lat'
⚠️ 資料插入失敗（站點 500111017）: 'lat'
⚠️ 資料插入失敗（站點 500111018）: 'lat'
⚠️ 資料插入失敗（站點 500111019）: 'lat'
⚠️ 資料插入失敗（站點 500111020）: 'lat'
⚠️ 資料插入失敗（站點 500111021）: 'lat'
⚠️ 資料插入失敗（站點 500111022）: 'lat'
⚠️ 資料插入失敗（站點 500111023）: 'lat'
⚠️ 資料插入失敗（站點 500111024）: 'lat'
⚠️ 資料插入失敗（站點 500111025）: 'lat'
⚠️ 資料插入失敗（站點 500111026）: 'lat'
⚠️ 資料插入失敗（站點 500111027）: 'lat'
⚠️ 資料插入失敗（站點 500111028）: 'lat'
⚠️ 資料插入失敗（站點 500111029）: 'lat'
⚠️ 資料插入失敗（站點 500111030）: 'lat'
⚠️ 資料插入失敗（站點 500111031）: 'lat'
⚠️ 資料插入失敗（站點 500111032）: 'lat'
⚠️ 資料插入失敗（站點 500111033）: 'lat'
⚠️ 資料插入失敗（站點 500111034）: 'lat'
⚠️ 資料插入失敗（站點 500111035）: 'lat'
⚠️ 資料插入失敗（站點 500111036）: 'lat'
⚠️ 資料插入失敗（站點 500111037）: 'lat'
⚠️ 資料插入失敗（站點 500111038）: 'lat'
⚠️ 資料插入失敗（站點 500111039）: 'lat'
⚠️ 資料插入失敗（站點 500111040）: 'lat'
⚠️ 資料插入失敗（站點 500111041）: 'lat'
⚠️ 資料插入失敗（站點 500111042）: 'lat'
⚠️ 資料插入失敗（站點 500111043）: 'lat'
⚠️ 資料插入失敗（站點 500111044）: 'lat'
⚠️ 資料插入失敗（站點 500111045）: 'lat'
⚠️ 資料插入失敗（站點 500111046）: 'lat'
⚠️ 資料插入失敗（站點 500111047）: 'lat'
⚠️ 資料插入失敗（站點 500111048）: 'lat'
⚠️ 資料插入失敗（站點 500111049）: 'lat'
⚠️ 資料插入失敗（站點 500111050）: 'lat'
⚠️ 資料插入失敗（站點 500111051）: 'lat'
⚠️ 資料插入失敗（站點 500111052）: 'lat'
⚠️ 資料插入失敗（站點 500111053）: 'lat'
⚠️ 資料插入失敗（站點 500111054）: 'lat'
⚠️ 資料插入失敗（站點 500111055）: 'lat'
⚠️ 資料插入失敗（站點 500111056）: 'lat'
⚠️ 資料插入失敗（站點 500111057）: 'lat'
⚠️ 資料插入失敗（站點 500111058）: 'lat'
⚠️ 資料插入失敗（站點 500111059）: 'lat'
⚠️ 資料插入失敗（站點 500111060）: 'lat'
⚠️ 資料插入失敗（站點 500111061）: 'lat'
⚠️ 資料插入失敗（站點 500111062）: 'lat'
⚠️ 資料插入失敗（站點 500111063）: 'lat'
⚠️ 資料插入失敗（站點 500111064）: 'lat'
⚠️ 資料插入失敗（站點 500111065）: 'lat'
⚠️ 資料插入失敗（站點 500111066）: 'lat'
⚠️ 資料插入失敗（站點 500111067）: 'lat'
⚠️ 資料插入失敗（站點 500111068）: 'lat'
⚠️ 資料插入失敗（站點 500111069）: 'lat'
⚠️ 資料插入失敗（站點 500111070）: 'lat'
⚠️ 資料插入失敗（站點 500111071）: 'lat'
⚠️ 資料插入失敗（站點 500111072）: 'lat'
⚠️ 資料插入失敗（站點 500111073）: 'lat'
⚠️ 資料插入失敗（站點 500111074）: 'lat'
⚠️ 資料插入失敗（站點 500111075）: 'lat'
⚠️ 資料插入失敗（站點 500111076）: 'lat'
⚠️ 資料插入失敗（站點 500111077）: 'lat'
⚠️ 資料插入失敗（站點 500111078）: 'lat'
⚠️ 資料插入失敗（站點 500111079）: 'lat'
⚠️ 資料插入失敗（站點 500111080）: 'lat'
⚠️ 資料插入失敗（站點 500111081）: 'lat'
⚠️ 資料插入失敗（站點 500111082）: 'lat'
⚠️ 資料插入失敗（站點 500111083）: 'lat'
⚠️ 資料插入失敗（站點 500111084）: 'lat'
⚠️ 資料插入失敗（站點 500111085）: 'lat'
⚠️ 資料插入失敗（站點 500111086）: 'lat'
⚠️ 資料插入失敗（站點 500111087）: 'lat'
⚠️ 資料插入失敗（站點 500111088）: 'lat'
⚠️ 資料插入失敗（站點 500111089）: 'lat'
⚠️ 資料插入失敗（站點 500111090）: 'lat'
⚠️ 資料插入失敗（站點 500111091）: 'lat'
⚠️ 資料插入失敗（站點 500111092）: 'lat'
⚠️ 資料插入失敗（站點 500111093）: 'lat'
⚠️ 資料插入失敗（站點 500111094）: 'lat'
⚠️ 資料插入失敗（站點 500111095）: 'lat'
⚠️ 資料插入失敗（站點 500111096）: 'lat'
⚠️ 資料插入失敗（站點 500111097）: 'lat'
⚠️ 資料插入失敗（站點 500111098）: 'lat'
⚠️ 資料插入失敗（站點 500111113）: 'lat'
⚠️ 資料插入失敗（站點 500111114）: 'lat'
⚠️ 資料插入失敗（站點 500111115）: 'lat'
⚠️ 資料插入失敗（站點 500111116）: 'lat'
⚠️ 資料插入失敗（站點 500111117）: 'lat'
⚠️ 資料插入失敗（站點 500111118）: 'lat'
⚠️ 資料插入失敗（站點 500111119）: 'lat'
⚠️ 資料插入失敗（站點 500111120）: 'lat'
⚠️ 資料插入失敗（站點 500111121）: 'lat'
⚠️ 資料插入失敗（站點 500111123）: 'lat'
⚠️ 資料插入失敗（站點 500111124）: 'lat'
⚠️ 資料插入失敗（站點 500112001）: 'lat'
⚠️ 資料插入失敗（站點 500112002）: 'lat'
⚠️ 資料插入失敗（站點 500112003）: 'lat'
⚠️ 資料插入失敗（站點 500112004）: 'lat'
⚠️ 資料插入失敗（站點 500112005）: 'lat'
⚠️ 資料插入失敗（站點 500112006）: 'lat'
⚠️ 資料插入失敗（站點 500112007）: 'lat'
⚠️ 資料插入失敗（站點 500112008）: 'lat'
⚠️ 資料插入失敗（站點 500112009）: 'lat'
⚠️ 資料插入失敗（站點 500112010）: 'lat'
⚠️ 資料插入失敗（站點 500112011）: 'lat'
⚠️ 資料插入失敗（站點 500112012）: 'lat'
⚠️ 資料插入失敗（站點 500112013）: 'lat'
⚠️ 資料插入失敗（站點 500112014）: 'lat'
⚠️ 資料插入失敗（站點 500112015）: 'lat'
⚠️ 資料插入失敗（站點 500112016）: 'lat'
⚠️ 資料插入失敗（站點 500112017）: 'lat'
⚠️ 資料插入失敗（站點 500112018）: 'lat'
⚠️ 資料插入失敗（站點 500112019）: 'lat'
⚠️ 資料插入失敗（站點 500112020）: 'lat'
⚠️ 資料插入失敗（站點 500112021）: 'lat'
⚠️ 資料插入失敗（站點 500112022）: 'lat'
⚠️ 資料插入失敗（站點 500112023）: 'lat'
⚠️ 資料插入失敗（站點 500112024）: 'lat'
⚠️ 資料插入失敗（站點 500112025）: 'lat'
⚠️ 資料插入失敗（站點 500112026）: 'lat'
⚠️ 資料插入失敗（站點 500112027）: 'lat'
⚠️ 資料插入失敗（站點 500112028）: 'lat'
⚠️ 資料插入失敗（站點 500112029）: 'lat'
⚠️ 資料插入失敗（站點 500112030）: 'lat'
⚠️ 資料插入失敗（站點 500112031）: 'lat'
⚠️ 資料插入失敗（站點 500112032）: 'lat'
⚠️ 資料插入失敗（站點 500112033）: 'lat'
⚠️ 資料插入失敗（站點 500112035）: 'lat'
⚠️ 資料插入失敗（站點 500112036）: 'lat'
⚠️ 資料插入失敗（站點 500112037）: 'lat'
⚠️ 資料插入失敗（站點 500112038）: 'lat'
⚠️ 資料插入失敗（站點 500112039）: 'lat'
⚠️ 資料插入失敗（站點 500112040）: 'lat'
⚠️ 資料插入失敗（站點 500112042）: 'lat'
⚠️ 資料插入失敗（站點 500112043）: 'lat'
⚠️ 資料插入失敗（站點 500112044）: 'lat'
⚠️ 資料插入失敗（站點 500112045）: 'lat'
⚠️ 資料插入失敗（站點 500112046）: 'lat'
⚠️ 資料插入失敗（站點 500112047）: 'lat'
⚠️ 資料插入失敗（站點 500112048）: 'lat'
⚠️ 資料插入失敗（站點 500112049）: 'lat'
⚠️ 資料插入失敗（站點 500112050）: 'lat'
⚠️ 資料插入失敗（站點 500112051）: 'lat'
⚠️ 資料插入失敗（站點 500112052）: 'lat'
⚠️ 資料插入失敗（站點 500112053）: 'lat'
⚠️ 資料插入失敗（站點 500112054）: 'lat'
⚠️ 資料插入失敗（站點 500112055）: 'lat'
⚠️ 資料插入失敗（站點 500112056）: 'lat'
⚠️ 資料插入失敗（站點 500112057）: 'lat'
⚠️ 資料插入失敗（站點 500112058）: 'lat'
⚠️ 資料插入失敗（站點 500112059）: 'lat'
⚠️ 資料插入失敗（站點 500112060）: 'lat'
⚠️ 資料插入失敗（站點 500112061）: 'lat'
⚠️ 資料插入失敗（站點 500112062）: 'lat'
⚠️ 資料插入失敗（站點 500112063）: 'lat'
⚠️ 資料插入失敗（站點 500112064）: 'lat'
⚠️ 資料插入失敗（站點 500112065）: 'lat'
⚠️ 資料插入失敗（站點 500112066）: 'lat'
⚠️ 資料插入失敗（站點 500112067）: 'lat'
⚠️ 資料插入失敗（站點 500112068）: 'lat'
⚠️ 資料插入失敗（站點 500112069）: 'lat'
⚠️ 資料插入失敗（站點 500112070）: 'lat'
⚠️ 資料插入失敗（站點 500112071）: 'lat'
⚠️ 資料插入失敗（站點 500112072）: 'lat'
⚠️ 資料插入失敗（站點 500112073）: 'lat'
⚠️ 資料插入失敗（站點 500112075）: 'lat'
⚠️ 資料插入失敗（站點 500112076）: 'lat'
⚠️ 資料插入失敗（站點 500112078）: 'lat'
⚠️ 資料插入失敗（站點 500112079）: 'lat'
⚠️ 資料插入失敗（站點 500112080）: 'lat'
⚠️ 資料插入失敗（站點 500112081）: 'lat'
⚠️ 資料插入失敗（站點 500112082）: 'lat'
⚠️ 資料插入失敗（站點 500112083）: 'lat'
⚠️ 資料插入失敗（站點 500112084）: 'lat'
⚠️ 資料插入失敗（站點 500112085）: 'lat'
⚠️ 資料插入失敗（站點 500112086）: 'lat'
⚠️ 資料插入失敗（站點 500112087）: 'lat'
⚠️ 資料插入失敗（站點 500112088）: 'lat'
⚠️ 資料插入失敗（站點 500112089）: 'lat'
⚠️ 資料插入失敗（站點 500112090）: 'lat'
⚠️ 資料插入失敗（站點 500112091）: 'lat'
⚠️ 資料插入失敗（站點 500112092）: 'lat'
⚠️ 資料插入失敗（站點 500112093）: 'lat'
⚠️ 資料插入失敗（站點 500112094）: 'lat'
⚠️ 資料插入失敗（站點 500112095）: 'lat'
⚠️ 資料插入失敗（站點 500112096）: 'lat'
⚠️ 資料插入失敗（站點 500112097）: 'lat'
⚠️ 資料插入失敗（站點 500112098）: 'lat'
⚠️ 資料插入失敗（站點 500112099）: 'lat'
⚠️ 資料插入失敗（站點 500112100）: 'lat'
⚠️ 資料插入失敗（站點 500112101）: 'lat'
⚠️ 資料插入失敗（站點 500112102）: 'lat'
⚠️ 資料插入失敗（站點 500112103）: 'lat'
⚠️ 資料插入失敗（站點 500112104）: 'lat'
⚠️ 資料插入失敗（站點 500112105）: 'lat'
⚠️ 資料插入失敗（站點 500112106）: 'lat'
⚠️ 資料插入失敗（站點 500112107）: 'lat'
⚠️ 資料插入失敗（站點 500112108）: 'lat'
⚠️ 資料插入失敗（站點 500112109）: 'lat'
⚠️ 資料插入失敗（站點 500112110）: 'lat'
⚠️ 資料插入失敗（站點 500112111）: 'lat'
⚠️ 資料插入失敗（站點 500112112）: 'lat'
⚠️ 資料插入失敗（站點 500112113）: 'lat'
⚠️ 資料插入失敗（站點 500112114）: 'lat'
⚠️ 資料插入失敗（站點 500112115）: 'lat'
⚠️ 資料插入失敗（站點 500112116）: 'lat'
⚠️ 資料插入失敗（站點 500112117）: 'lat'
⚠️ 資料插入失敗（站點 500112118）: 'lat'
⚠️ 資料插入失敗（站點 500112119）: 'lat'
⚠️ 資料插入失敗（站點 500112120）: 'lat'
⚠️ 資料插入失敗（站點 500112123）: 'lat'
⚠️ 資料插入失敗（站點 500112124）: 'lat'
⚠️ 資料插入失敗（站點 500112125）: 'lat'
⚠️ 資料插入失敗（站點 500112127）: 'lat'
⚠️ 資料插入失敗（站點 500112128）: 'lat'
⚠️ 資料插入失敗（站點 500113001）: 'lat'
⚠️ 資料插入失敗（站點 500113002）: 'lat'
⚠️ 資料插入失敗（站點 500113003）: 'lat'
⚠️ 資料插入失敗（站點 500113004）: 'lat'
⚠️ 資料插入失敗（站點 500113005）: 'lat'
⚠️ 資料插入失敗（站點 500113006）: 'lat'
⚠️ 資料插入失敗（站點 500113007）: 'lat'
⚠️ 資料插入失敗（站點 500113008）: 'lat'
⚠️ 資料插入失敗（站點 500113009）: 'lat'
⚠️ 資料插入失敗（站點 500113010）: 'lat'
⚠️ 資料插入失敗（站點 500113012）: 'lat'
⚠️ 資料插入失敗（站點 500113013）: 'lat'
⚠️ 資料插入失敗（站點 500113014）: 'lat'
⚠️ 資料插入失敗（站點 500113015）: 'lat'
⚠️ 資料插入失敗（站點 500113016）: 'lat'
⚠️ 資料插入失敗（站點 500113017）: 'lat'
⚠️ 資料插入失敗（站點 500113018）: 'lat'
⚠️ 資料插入失敗（站點 500113019）: 'lat'
⚠️ 資料插入失敗（站點 500113020）: 'lat'
⚠️ 資料插入失敗（站點 500113022）: 'lat'
⚠️ 資料插入失敗（站點 500113023）: 'lat'
⚠️ 資料插入失敗（站點 500113025）: 'lat'
⚠️ 資料插入失敗（站點 500113026）: 'lat'
⚠️ 資料插入失敗（站點 500113027）: 'lat'
⚠️ 資料插入失敗（站點 500113028）: 'lat'
⚠️ 資料插入失敗（站點 500113029）: 'lat'
⚠️ 資料插入失敗（站點 500113030）: 'lat'
⚠️ 資料插入失敗（站點 500113031）: 'lat'
⚠️ 資料插入失敗（站點 500113032）: 'lat'
⚠️ 資料插入失敗（站點 500113033）: 'lat'
⚠️ 資料插入失敗（站點 500113034）: 'lat'
⚠️ 資料插入失敗（站點 500113035）: 'lat'
⚠️ 資料插入失敗（站點 500113036）: 'lat'
⚠️ 資料插入失敗（站點 500113037）: 'lat'
⚠️ 資料插入失敗（站點 500113038）: 'lat'
⚠️ 資料插入失敗（站點 500113039）: 'lat'
⚠️ 資料插入失敗（站點 500113040）: 'lat'
⚠️ 資料插入失敗（站點 500113041）: 'lat'
⚠️ 資料插入失敗（站點 500113042）: 'lat'
⚠️ 資料插入失敗（站點 500113043）: 'lat'
⚠️ 資料插入失敗（站點 500113044）: 'lat'
⚠️ 資料插入失敗（站點 500113045）: 'lat'
⚠️ 資料插入失敗（站點 500113046）: 'lat'
⚠️ 資料插入失敗（站點 500113047）: 'lat'
⚠️ 資料插入失敗（站點 500113048）: 'lat'
⚠️ 資料插入失敗（站點 500113049）: 'lat'
⚠️ 資料插入失敗（站點 500113050）: 'lat'
⚠️ 資料插入失敗（站點 500113051）: 'lat'
⚠️ 資料插入失敗（站點 500113052）: 'lat'
⚠️ 資料插入失敗（站點 500113053）: 'lat'
⚠️ 資料插入失敗（站點 500113054）: 'lat'
⚠️ 資料插入失敗（站點 500113055）: 'lat'
⚠️ 資料插入失敗（站點 500113056）: 'lat'
⚠️ 資料插入失敗（站點 500113057）: 'lat'
⚠️ 資料插入失敗（站點 500113058）: 'lat'
⚠️ 資料插入失敗（站點 500113059）: 'lat'
⚠️ 資料插入失敗（站點 500113060）: 'lat'
⚠️ 資料插入失敗（站點 500113061）: 'lat'
⚠️ 資料插入失敗（站點 500113062）: 'lat'
⚠️ 資料插入失敗（站點 500113063）: 'lat'
⚠️ 資料插入失敗（站點 500113064）: 'lat'
⚠️ 資料插入失敗（站點 500113065）: 'lat'
⚠️ 資料插入失敗（站點 500113066）: 'lat'
⚠️ 資料插入失敗（站點 500113068）: 'lat'
⚠️ 資料插入失敗（站點 500113069）: 'lat'
⚠️ 資料插入失敗（站點 500113070）: 'lat'
⚠️ 資料插入失敗（站點 500113071）: 'lat'
⚠️ 資料插入失敗（站點 500113072）: 'lat'
⚠️ 資料插入失敗（站點 500113073）: 'lat'
⚠️ 資料插入失敗（站點 500113074）: 'lat'
⚠️ 資料插入失敗（站點 500113075）: 'lat'
⚠️ 資料插入失敗（站點 500113077）: 'lat'
⚠️ 資料插入失敗（站點 500113078）: 'lat'
⚠️ 資料插入失敗（站點 500113079）: 'lat'
⚠️ 資料插入失敗（站點 500113080）: 'lat'
⚠️ 資料插入失敗（站點 500113081）: 'lat'
⚠️ 資料插入失敗（站點 500113083）: 'lat'
⚠️ 資料插入失敗（站點 500113085）: 'lat'
⚠️ 資料插入失敗（站點 500113086）: 'lat'
⚠️ 資料插入失敗（站點 500113087）: 'lat'
⚠️ 資料插入失敗（站點 500113088）: 'lat'
⚠️ 資料插入失敗（站點 500113089）: 'lat'
⚠️ 資料插入失敗（站點 500113090）: 'lat'
⚠️ 資料插入失敗（站點 500113091）: 'lat'
⚠️ 資料插入失敗（站點 500113092）: 'lat'
⚠️ 資料插入失敗（站點 500113093）: 'lat'
⚠️ 資料插入失敗（站點 500119005）: 'lat'
⚠️ 資料插入失敗（站點 500119006）: 'lat'
⚠️ 資料插入失敗（站點 500119007）: 'lat'
⚠️ 資料插入失敗（站點 500119008）: 'lat'
⚠️ 資料插入失敗（站點 500119009）: 'lat'
⚠️ 資料插入失敗（站點 500119043）: 'lat'
⚠️ 資料插入失敗（站點 500119044）: 'lat'
⚠️ 資料插入失敗（站點 500119045）: 'lat'
⚠️ 資料插入失敗（站點 500119046）: 'lat'
⚠️ 資料插入失敗（站點 500119047）: 'lat'
⚠️ 資料插入失敗（站點 500119048）: 'lat'
⚠️ 資料插入失敗（站點 500119049）: 'lat'
⚠️ 資料插入失敗（站點 500119050）: 'lat'
⚠️ 資料插入失敗（站點 500119051）: 'lat'
⚠️ 資料插入失敗（站點 500119052）: 'lat'
⚠️ 資料插入失敗（站點 500119053）: 'lat'
⚠️ 資料插入失敗（站點 500119054）: 'lat'
⚠️ 資料插入失敗（站點 500119055）: 'lat'
⚠️ 資料插入失敗（站點 500119056）: 'lat'
⚠️ 資料插入失敗（站點 500119057）: 'lat'
⚠️ 資料插入失敗（站點 500119058）: 'lat'
⚠️ 資料插入失敗（站點 500119059）: 'lat'
⚠️ 資料插入失敗（站點 500119060）: 'lat'
⚠️ 資料插入失敗（站點 500119061）: 'lat'
⚠️ 資料插入失敗（站點 500119062）: 'lat'
⚠️ 資料插入失敗（站點 500119063）: 'lat'
⚠️ 資料插入失敗（站點 500119064）: 'lat'
⚠️ 資料插入失敗（站點 500119065）: 'lat'
⚠️ 資料插入失敗（站點 500119066）: 'lat'
⚠️ 資料插入失敗（站點 500119067）: 'lat'
⚠️ 資料插入失敗（站點 500119068）: 'lat'
⚠️ 資料插入失敗（站點 500119069）: 'lat'
⚠️ 資料插入失敗（站點 500119070）: 'lat'
⚠️ 資料插入失敗（站點 500119071）: 'lat'
⚠️ 資料插入失敗（站點 500119072）: 'lat'
⚠️ 資料插入失敗（站點 500119074）: 'lat'
⚠️ 資料插入失敗（站點 500119075）: 'lat'
⚠️ 資料插入失敗（站點 500119076）: 'lat'
⚠️ 資料插入失敗（站點 500119077）: 'lat'
⚠️ 資料插入失敗（站點 500119078）: 'lat'
⚠️ 資料插入失敗（站點 500119079）: 'lat'
⚠️ 資料插入失敗（站點 500119080）: 'lat'
⚠️ 資料插入失敗（站點 500119081）: 'lat'
⚠️ 資料插入失敗（站點 500119082）: 'lat'
⚠️ 資料插入失敗（站點 500119083）: 'lat'
⚠️ 資料插入失敗（站點 500119084）: 'lat'
⚠️ 資料插入失敗（站點 500119085）: 'lat'
⚠️ 資料插入失敗（站點 500119086）: 'lat'
⚠️ 資料插入失敗（站點 500119087）: 'lat'
⚠️ 資料插入失敗（站點 500119088）: 'lat'
⚠️ 資料插入失敗（站點 500119089）: 'lat'
⚠️ 資料插入失敗（站點 500119090）: 'lat'
⚠️ 資料插入失敗（站點 500119091）: 'lat'
⚠️ 資料插入失敗（站點 500119092）: 'lat'
⚠️ 資料插入失敗（站點 500119093）: 'lat'
⚠️ 資料插入失敗（站點 500119094）: 'lat'
⚠️ 資料插入失敗（站點 500119095）: 'lat'
⚠️ 資料插入失敗（站點 500119096）: 'lat'
⚠️ 資料插入失敗（站點 500119097）: 'lat'
✅ 本次資料成功處理完畢！
[2025-06-20 17:48:01] 本次資料成功處理完畢
[2025-06-20 17:49:01] 本次資料成功處理完畢
[2025-06-20 17:50:01] 本次資料成功處理完畢
[2025-06-20 17:51:01] 本次資料成功處理完畢
[2025-06-20 17:52:01] 本次資料成功處理完畢
[2025-06-20 17:53:01] 本次資料成功處理完畢
[2025-06-20 17:54:02] 本次資料成功處理完畢
[2025-06-20 17:55:06] 本次資料成功處理完畢
[2025-06-20 17:56:02] 本次資料成功處理完畢
[2025-06-20 17:57:02] 本次資料成功處理完畢
[2025-06-20 17:58:02] 本次資料成功處理完畢
[2025-06-20 17:59:05] 本次資料成功處理完畢
[2025-06-20 18:00:03] 本次資料成功處理完畢
[2025-06-20 18:01:01] 本次資料成功處理完畢
[2025-06-20 18:02:01] 本次資料成功處理完畢
[2025-06-20 18:03:01] [2025-06-20 18:03:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1801.png
[2025-06-20 18:04:01] [2025-06-20 18:04:01] ✅ 熱點圖已儲存為 youbike_map_20250620_1801.png
本次資料成功處理完畢
[2025-06-20 18:05:01] [2025-06-20 18:05:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1803.png
[2025-06-20 18:06:02] [2025-06-20 18:06:02] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1804.png
[2025-06-20 18:07:01] [2025-06-20 18:07:01] ✅ 熱點圖已儲存為 youbike_map_20250620_1804.png
本次資料成功處理完畢
[2025-06-20 18:08:02] [2025-06-20 18:08:02] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += int(row['available_rent_bikes'])/int(row['total'])
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:09:01] [2025-06-20 18:09:01] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += int(row['available_rent_bikes'])/int(row['total'])
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:10:01] [2025-06-20 18:10:01] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += int(row['available_rent_bikes'])/int(row['total'])
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:11:01] [2025-06-20 18:11:01] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += float(row['available_rent_bikes']) / float(row['total']) if row['total'] else 0
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
抓取資料失敗: HTTPSConnectionPool(host='tcgbusfs.blob.core.windows.net', port=443): Max retries exceeded with url: /dotapp/youbike/v2/youbike_immediate.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'tcgbusfs.blob.core.windows.net'. (_ssl.c:1149)")))
[2025-06-20 18:12:01] [2025-06-20 18:12:01] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += float(row['available_rent_bikes']) / float(row['total']) if row['total'] else 0
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:13:01] [2025-06-20 18:13:01] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += float(row['available_rent_bikes']) / float(row['total']) if row['total'] else 0
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:14:01] [2025-06-20 18:14:01] 本次資料成功處理完畢
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += float(row['available_rent_bikes']) / float(row['total']) if row['total'] else 0
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
[2025-06-20 18:15:01] [2025-06-20 18:15:01] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 52, in <module>
    grid[lat_idx, lon_idx] += float(row['available_rent_bikes']) / float(row['total']) if row['total'] else 0
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'total'
本次資料成功處理完畢
[2025-06-20 18:16:08] [2025-06-20 18:16:08] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1814.png
[2025-06-20 18:17:03] [2025-06-20 18:17:03] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1815.png
[2025-06-20 18:18:09] [2025-06-20 18:18:09] ✅ 熱點圖已儲存為 youbike_map_20250620_1815.png
本次資料成功處理完畢
[2025-06-20 18:19:01] [2025-06-20 18:19:01]   File "/app/createMap.py", line 63
    vmin=0,  # 顏色對應最小值為 0
    ^
SyntaxError: invalid syntax
本次資料成功處理完畢
[2025-06-20 18:20:05] [2025-06-20 18:20:05] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1818.png
[2025-06-20 18:21:01] [2025-06-20 18:21:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1819.png
[2025-06-20 18:22:01] [2025-06-20 18:22:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1820.png
[2025-06-20 18:23:02] [2025-06-20 18:23:02] ✅ 熱點圖已儲存為 youbike_map_20250620_1820.png
本次資料成功處理完畢
[2025-06-20 18:24:01] [2025-06-20 18:24:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1822.png
[2025-06-20 18:25:02] [2025-06-20 18:25:02] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1823.png
[2025-06-20 18:26:01] [2025-06-20 18:26:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1824.png
[2025-06-20 18:27:02] [2025-06-20 18:27:02] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1825.png
[2025-06-20 18:28:01] [2025-06-20 18:28:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1826.png
[2025-06-20 18:29:02] [2025-06-20 18:29:02] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1827.png
[2025-06-20 18:37:27] [2025-06-20 18:37:27] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
抓取資料失敗: HTTPSConnectionPool(host='tcgbusfs.blob.core.windows.net', port=443): Max retries exceeded with url: /dotapp/youbike/v2/youbike_immediate.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b54679997c0>: Failed to resolve 'tcgbusfs.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))
[2025-06-20 18:38:02] [2025-06-20 18:38:02] ✅ 熱點圖已儲存為 youbike_map_20250620_1827.png
抓取資料失敗: HTTPSConnectionPool(host='tcgbusfs.blob.core.windows.net', port=443): Max retries exceeded with url: /dotapp/youbike/v2/youbike_immediate.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b30fdf777c0>: Failed to resolve 'tcgbusfs.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))
[2025-06-20 18:39:01] [2025-06-20 18:39:01] ✅ 熱點圖已儲存為 youbike_map_20250620_1827.png
[2025-06-20 18:40:03] [2025-06-20 18:40:03] ✅ 熱點圖已儲存為 youbike_map_20250620_1827.png
本次資料成功處理完畢
[2025-06-20 18:42:01] [2025-06-20 18:42:01] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
抓取資料失敗: HTTPSConnectionPool(host='tcgbusfs.blob.core.windows.net', port=443): Max retries exceeded with url: /dotapp/youbike/v2/youbike_immediate.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ee057ed17c0>: Failed to resolve 'tcgbusfs.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))
[2025-06-20 18:43:00] [2025-06-20 18:43:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-20 18:45:02] [2025-06-20 18:45:02] 資料庫連線失敗: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-20 18:47:02] [2025-06-20 18:47:02] 資料庫連線失敗: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-20 18:48:01] [2025-06-20 18:48:01] 資料庫連線失敗: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/createMap.py", line 23, in <module>
    latest_time = pd.read_sql("""
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 633, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3273, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "192.168.56.101", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-20 18:49:01] [2025-06-20 18:49:01] ✅ 熱點圖已儲存為 youbike_map_20250620_1839.png
抓取資料失敗: HTTPSConnectionPool(host='tcgbusfs.blob.core.windows.net', port=443): Max retries exceeded with url: /dotapp/youbike/v2/youbike_immediate.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x77fd3a12a7c0>: Failed to resolve 'tcgbusfs.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))
[2025-06-20 18:50:01] [2025-06-20 18:50:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1848.png
[2025-06-20 18:51:01] [2025-06-20 18:51:01] 本次資料成功處理完畢
✅ 熱點圖已儲存為 youbike_map_20250620_1849.png
